import { LangCode } from "./translations";

interface AboutTexts {
  heroTitle: string; heroSub: string;
  missionLabel: string; missionTitle: string; missionTitleRed: string; missionSub: string;
  card1t: string; card1d: string; card2t: string; card2d: string; card3t: string; card3d: string;
  storyLabel: string; storyTitle: string; story1: string; story2: string; story3: string;
  valuesLabel: string; valuesTitle: string;
  v: Array<{ emoji: string; t: string; d: string }>;
  statsTitle: string;
  stats: Array<{ icon: string; value: string; label: string }>;
  toneLabel: string; toneTitle: string; toneSub: string;
  tones: Array<{ wrong: string; right: string }>;
  secTitle: string; secDesc: string;
  secFeatures: string[];
  ctaTitle: string; ctaSub: string;
}

const texts: Partial<Record<LangCode, AboutTexts>> = {
  ru: {
    heroTitle: "О нас",
    heroSub: "Мы не строим платформу для аренды жилья.\nМы строим живую культурную сеть.",
    missionLabel: "Наша миссия",
    missionTitle: "Армения открывается",
    missionTitleRed: "через сердце семьи",
    missionSub: "HayHome — это не Airbnb для Армении. Это нечто большее — культурная экосистема национального масштаба. Мы сохраняем армянские семейные ценности, передаём культурный код и укрепляем образ Армении как самого гостеприимного народа мира с великой кухней и историей.",
    card1t: "Сохранение традиций", card1d: "Каждая семья — хранитель культурного кода. Мы помогаем этому коду жить и передаваться следующим поколениям.",
    card2t: "Объединение народов", card2d: "Гости из 40+ стран уже познакомились с Арменией через наших хозяев. Каждый визит — маленький мост между культурами.",
    card3t: "Гордость за свою страну", card3d: "Армянские семьи зарабатывают статус «Хранителя традиций» — и с гордостью несут его как признание сообщества.",
    storyLabel: "Как всё началось",
    storyTitle: "Идея, которая родилась за ужином",
    story1: "Всё началось с простого наблюдения: в Армении живут сотни семей, готовых принять гостей, угостить по-армянски и показать настоящее гостеприимство. Но у них не было инструмента, чтобы рассказать об этом миру.",
    story2: "А туристы со всего мира хотят именно этого — не отельный сервис, а живой опыт. Не стоковые улыбки, а настоящие истории за большим столом.",
    story3: "HayHome создан, чтобы соединить этих людей. Это платформа доверия, культуры и тепла. Не просто бизнес — движение.",
    valuesLabel: "Наши ценности", valuesTitle: "Чем мы не Airbnb",
    v: [
      { emoji: "🏡", t: "Хозяин — не арендодатель", d: "Каждый хозяин — «Хранитель традиций». Он не сдаёт комнату, он презентует свой уклад жизни, культуру и историю." },
      { emoji: "🍽️", t: "Опыт, а не кровать", d: "Гость ищет уникальный опыт: мастер-классы, совместные ужины, истории." },
      { emoji: "✅", t: "Доверие через верификацию", d: "Каждая семья проходит проверку. Система звёзд гарантирует качество." },
      { emoji: "🌍", t: "Армяне знакомят армян", d: "Армянские семьи из разных регионов знакомятся через платформу." },
      { emoji: "🎖️", t: "Геймификация и статусы", d: "Бейджи «Лучшая кухня», «Мастер вина» — признание сообщества." },
      { emoji: "📖", t: "Истории, не отзывы", d: "«Я приехал туристом, а уехал сыном этой семьи» — вот настоящий отзыв." },
    ],
    statsTitle: "HayHome сегодня",
    stats: [
      { icon: "🏡", value: "5+", label: "Семей в сети" },
      { icon: "🗺️", value: "10+", label: "Регионов Армении" },
      { icon: "🌍", value: "40+", label: "Стран гостей" },
      { icon: "⭐", value: "4.9★", label: "Средний рейтинг" },
    ],
    toneLabel: "Наш голос", toneTitle: "Как мы говорим",
    toneSub: "Мы говорим как старший брат, гостеприимный хозяин, патриот без пафоса — не как корпорация",
    tones: [
      { wrong: "«Воспользуйтесь нашим сервисом»", right: "«Зайди — мы ждём»" },
      { wrong: "«Высококвалифицированные хосты»", right: "«Семья Арутюнян из Еревана»" },
      { wrong: "«Оставьте отзыв»", right: "«Расскажи свою историю»" },
      { wrong: "«Оформить бронирование»", right: "«Договориться с семьёй»" },
    ],
    secTitle: "Безопасность и доверие",
    secDesc: "Каждая семья проходит верификацию документов. Первый гостевой визит — под контролем платформы. Страхование и поддержка 24/7.",
    secFeatures: ["✅ Проверка документов", "🔒 Безопасные платежи", "📞 Поддержка 24/7", "⭐ Рейтинг и отзывы"],
    ctaTitle: "Войди — стань частью большой армянской семьи",
    ctaSub: "Не важно откуда вы. Важно что вы готовы открыться новому.",
  },
  en: {
    heroTitle: "About Us",
    heroSub: "We are not building a rental platform.\nWe are building a living cultural network.",
    missionLabel: "Our Mission",
    missionTitle: "Armenia opens up",
    missionTitleRed: "through the heart of a family",
    missionSub: "HayHome is not Airbnb. It is a cultural ecosystem of national scale. We preserve Armenian family values and strengthen Armenia's image as the most hospitable people in the world with a great cuisine and history.",
    card1t: "Preserving Traditions", card1d: "Every family is a keeper of cultural heritage. We help this heritage live and pass on to future generations.",
    card2t: "Uniting People", card2d: "Guests from 40+ countries have already discovered Armenia through our hosts. Every visit is a bridge between cultures.",
    card3t: "Pride in the Country", card3d: "Armenian families earn the status of 'Tradition Keeper' — community recognition they wear with pride.",
    storyLabel: "How It Started",
    storyTitle: "An idea born over dinner",
    story1: "It all started with a simple observation: hundreds of Armenian families are ready to welcome guests and show real hospitality — but had no tool to tell the world about it.",
    story2: "And tourists from around the world want exactly this — not a hotel service, but a living experience. Real stories around a big table.",
    story3: "HayHome was created to connect these people. It is a platform of trust, culture and warmth. Not just a business — a movement.",
    valuesLabel: "Our Values", valuesTitle: "Why We Are Not Airbnb",
    v: [
      { emoji: "🏡", t: "Host, Not Landlord", d: "Every host is a 'Tradition Keeper'. They present their way of life, culture, cuisine and history." },
      { emoji: "🍽️", t: "Experience, Not a Bed", d: "The guest seeks a unique experience: masterclasses, shared dinners, stories to tell their children." },
      { emoji: "✅", t: "Trust Through Verification", d: "Every family is verified. The star system guarantees quality." },
      { emoji: "🌍", t: "Armenians Meet Armenians", d: "Armenian families from different regions discover each other through the platform." },
      { emoji: "🎖️", t: "Gamification & Status", d: "Badges like 'Best Kitchen', 'Wine Master' — community recognition, not just icons." },
      { emoji: "📖", t: "Stories, Not Reviews", d: "'I came as a tourist and left as their son' — that's a real review." },
    ],
    statsTitle: "HayHome Today",
    stats: [
      { icon: "🏡", value: "5+", label: "Families in the network" },
      { icon: "🗺️", value: "10+", label: "Regions of Armenia" },
      { icon: "🌍", value: "40+", label: "Guest countries" },
      { icon: "⭐", value: "4.9★", label: "Average rating" },
    ],
    toneLabel: "Our Voice", toneTitle: "How We Speak",
    toneSub: "We speak like an older brother, a welcoming host, a patriot without pomposity — not like a corporation",
    tones: [
      { wrong: "\"Use our service\"", right: "\"Come in — we are waiting\"" },
      { wrong: "\"Highly qualified hosts\"", right: "\"Arutunyan family from Yerevan\"" },
      { wrong: "\"Leave a review\"", right: "\"Tell your story\"" },
      { wrong: "\"Make a booking\"", right: "\"Arrange with the family\"" },
    ],
    secTitle: "Safety & Trust",
    secDesc: "Every family goes through document verification. The first guest visit is monitored by the platform. Insurance and 24/7 support.",
    secFeatures: ["✅ Document verification", "🔒 Secure payments", "📞 24/7 support", "⭐ Ratings & reviews"],
    ctaTitle: "Come in — become part of one big Armenian family",
    ctaSub: "It doesn't matter where you are from. What matters is that you are ready to open up to something new.",
  },
  fr: {
    heroTitle: "À propos", heroSub: "Nous ne construisons pas une plateforme de location.\nNous construisons un réseau culturel vivant.",
    missionLabel: "Notre mission", missionTitle: "L'Arménie s'ouvre", missionTitleRed: "par le cœur d'une famille",
    missionSub: "HayHome n'est pas Airbnb. C'est quelque chose de plus — un écosystème culturel d'envergure nationale. Nous préservons les valeurs familiales arméniennes.",
    card1t: "Préserver les traditions", card1d: "Chaque famille est gardienne du code culturel. Nous aidons ce code à vivre et à se transmettre.",
    card2t: "Unir les peuples", card2d: "Des hôtes de 40+ pays ont déjà découvert l'Arménie grâce à nos familles.",
    card3t: "Fierté nationale", card3d: "Les familles arméniennes gagnent le statut de «Gardien des traditions» — reconnaissance de la communauté.",
    storyLabel: "Comment tout a commencé", storyTitle: "Une idée née autour d'un dîner",
    story1: "Tout a commencé par une simple observation: des centaines de familles arméniennes sont prêtes à accueillir des hôtes — mais n'avaient pas l'outil pour en parler au monde.",
    story2: "Et les touristes du monde entier veulent exactement cela — pas un service hôtelier, mais une expérience vivante.",
    story3: "HayHome a été créé pour connecter ces personnes. C'est une plateforme de confiance, de culture et de chaleur.",
    valuesLabel: "Nos valeurs", valuesTitle: "Pourquoi nous ne sommes pas Airbnb",
    v: [
      { emoji: "🏡", t: "Hôte, pas propriétaire", d: "Chaque hôte est un «Gardien des traditions». Il présente son mode de vie et sa culture." },
      { emoji: "🍽️", t: "Expérience, pas un lit", d: "L'hôte cherche une expérience unique: cours de cuisine, dîners partagés, histoires." },
      { emoji: "✅", t: "Confiance par vérification", d: "Chaque famille est vérifiée. Le système d'étoiles garantit la qualité." },
      { emoji: "🌍", t: "Les Arméniens se retrouvent", d: "Les familles arméniennes de différentes régions se découvrent via la plateforme." },
      { emoji: "🎖️", t: "Gamification et statuts", d: "Badges «Meilleure cuisine», «Maître vigneron» — reconnaissance de la communauté." },
      { emoji: "📖", t: "Histoires, pas des avis", d: "«Je suis venu touriste et je suis reparti comme leur fils» — voilà un vrai avis." },
    ],
    statsTitle: "HayHome aujourd'hui",
    stats: [
      { icon: "🏡", value: "5+", label: "Familles en réseau" }, { icon: "🗺️", value: "10+", label: "Régions d'Arménie" },
      { icon: "🌍", value: "40+", label: "Pays des hôtes" }, { icon: "⭐", value: "4.9★", label: "Note moyenne" },
    ],
    toneLabel: "Notre voix", toneTitle: "Comment nous parlons",
    toneSub: "Nous parlons comme un grand frère, un hôte accueillant, un patriote sans arrogance — pas comme une entreprise",
    tones: [
      { wrong: "«Utilisez notre service»", right: "«Entrez — nous attendons»" },
      { wrong: "«Hôtes hautement qualifiés»", right: "«Famille Arutunyan d'Erevan»" },
      { wrong: "«Laissez un avis»", right: "«Racontez votre histoire»" },
      { wrong: "«Effectuer une réservation»", right: "«S'arranger avec la famille»" },
    ],
    secTitle: "Sécurité et confiance", secDesc: "Chaque famille est vérifiée. Assurance et support 24/7.",
    secFeatures: ["✅ Vérification des documents", "🔒 Paiements sécurisés", "📞 Support 24/7", "⭐ Notes & avis"],
    ctaTitle: "Entrez — devenez membre d'une grande famille arménienne",
    ctaSub: "Peu importe d'où vous venez. Ce qui compte, c'est votre ouverture au nouveau.",
  },
  de: {
    heroTitle: "Über uns", heroSub: "Wir bauen keine Vermietungsplattform.\nWir bauen ein lebendiges Kulturnetzwerk.",
    missionLabel: "Unsere Mission", missionTitle: "Armenien öffnet sich", missionTitleRed: "durch das Herz einer Familie",
    missionSub: "HayHome ist kein Airbnb. Es ist ein kulturelles Ökosystem nationalen Ausmaßes.",
    card1t: "Traditionen bewahren", card1d: "Jede Familie ist Hüterin des kulturellen Codes.", card2t: "Völker verbinden", card2d: "Gäste aus 40+ Ländern haben Armenien bereits entdeckt.",
    card3t: "Nationaler Stolz", card3d: "Armenische Familien erhalten den Status «Hüter der Traditionen».",
    storyLabel: "Wie alles begann", storyTitle: "Eine Idee, die beim Abendessen entstand",
    story1: "Alles begann mit einer einfachen Beobachtung: Hunderte armenischer Familien sind bereit, Gäste aufzunehmen.",
    story2: "Und Touristen aus aller Welt wollen genau das — kein Hotelservice, sondern ein lebendiges Erlebnis.",
    story3: "HayHome wurde geschaffen, um diese Menschen zu verbinden. Eine Plattform des Vertrauens, der Kultur und der Wärme.",
    valuesLabel: "Unsere Werte", valuesTitle: "Warum wir kein Airbnb sind",
    v: [
      { emoji: "🏡", t: "Gastgeber, kein Vermieter", d: "Jeder Gastgeber ist ein «Hüter der Traditionen»." },
      { emoji: "🍽️", t: "Erlebnis, kein Bett", d: "Der Gast sucht ein einzigartiges Erlebnis." },
      { emoji: "✅", t: "Vertrauen durch Verifizierung", d: "Jede Familie wird überprüft." },
      { emoji: "🌍", t: "Armenier treffen Armenier", d: "Armenische Familien aus verschiedenen Regionen lernen sich kennen." },
      { emoji: "🎖️", t: "Gamification & Status", d: "Abzeichen wie «Beste Küche» — Gemeinschaftsanerkennung." },
      { emoji: "📖", t: "Geschichten, keine Bewertungen", d: "«Ich kam als Tourist und ging als ihr Sohn» — das ist eine echte Bewertung." },
    ],
    statsTitle: "HayHome heute",
    stats: [
      { icon: "🏡", value: "5+", label: "Familien im Netzwerk" }, { icon: "🗺️", value: "10+", label: "Regionen Armeniens" },
      { icon: "🌍", value: "40+", label: "Gastländer" }, { icon: "⭐", value: "4.9★", label: "Durchschnittsbewertung" },
    ],
    toneLabel: "Unsere Stimme", toneTitle: "Wie wir sprechen",
    toneSub: "Wir sprechen wie ein älterer Bruder, ein gastfreundlicher Wirt — nicht wie ein Unternehmen",
    tones: [
      { wrong: "«Nutzen Sie unseren Service»", right: "«Komm rein — wir warten»" },
      { wrong: "«Hochqualifizierte Gastgeber»", right: "«Familie Arutunyan aus Jerewan»" },
      { wrong: "«Bewertung abgeben»", right: "«Erzähl deine Geschichte»" },
      { wrong: "«Buchung vornehmen»", right: "«Mit der Familie arrangieren»" },
    ],
    secTitle: "Sicherheit & Vertrauen", secDesc: "Jede Familie wird überprüft. Versicherung und 24/7-Support.",
    secFeatures: ["✅ Dokumentenprüfung", "🔒 Sichere Zahlungen", "📞 24/7 Support", "⭐ Bewertungen"],
    ctaTitle: "Komm rein — werde Teil einer großen armenischen Familie",
    ctaSub: "Es spielt keine Rolle, woher Sie kommen. Was zählt, ist Ihre Offenheit.",
  },
  es: {
    heroTitle: "Sobre nosotros", heroSub: "No construimos una plataforma de alquiler.\nConstruimos una red cultural viva.",
    missionLabel: "Nuestra misión", missionTitle: "Armenia se abre", missionTitleRed: "a través del corazón de una familia",
    missionSub: "HayHome no es Airbnb. Es algo más — un ecosistema cultural de escala nacional.",
    card1t: "Preservar tradiciones", card1d: "Cada familia es guardiana del código cultural.", card2t: "Unir pueblos", card2d: "Huéspedes de 40+ países ya descubrieron Armenia.",
    card3t: "Orgullo nacional", card3d: "Las familias armenias ganan el estatus de «Guardián de tradiciones».",
    storyLabel: "Cómo empezó todo", storyTitle: "Una idea nacida en la cena",
    story1: "Todo comenzó con una simple observación: cientos de familias armenias están listas para recibir huéspedes.", story2: "Y los turistas de todo el mundo quieren exactamente eso — no servicio de hotel, sino experiencia viva.",
    story3: "HayHome fue creado para conectar a estas personas. Una plataforma de confianza, cultura y calidez.",
    valuesLabel: "Nuestros valores", valuesTitle: "Por qué no somos Airbnb",
    v: [
      { emoji: "🏡", t: "Anfitrión, no arrendador", d: "Cada anfitrión es un «Guardián de tradiciones»." },
      { emoji: "🍽️", t: "Experiencia, no cama", d: "El huésped busca una experiencia única." },
      { emoji: "✅", t: "Confianza por verificación", d: "Cada familia es verificada." },
      { emoji: "🌍", t: "Armenios conocen armenios", d: "Familias armenias de diferentes regiones se conocen." },
      { emoji: "🎖️", t: "Gamificación y estatus", d: "Insignias como «Mejor cocina» — reconocimiento comunitario." },
      { emoji: "📖", t: "Historias, no reseñas", d: "«Vine como turista y me fui como su hijo» — esa es una reseña real." },
    ],
    statsTitle: "HayHome hoy",
    stats: [
      { icon: "🏡", value: "5+", label: "Familias en la red" }, { icon: "🗺️", value: "10+", label: "Regiones de Armenia" },
      { icon: "🌍", value: "40+", label: "Países de huéspedes" }, { icon: "⭐", value: "4.9★", label: "Calificación media" },
    ],
    toneLabel: "Nuestra voz", toneTitle: "Cómo hablamos",
    toneSub: "Hablamos como un hermano mayor, un anfitrión acogedor — no como una corporación",
    tones: [
      { wrong: "«Use nuestro servicio»", right: "«Entra — te esperamos»" },
      { wrong: "«Anfitriones altamente cualificados»", right: "«Familia Arutunyan de Ereván»" },
      { wrong: "«Deja una reseña»", right: "«Cuenta tu historia»" },
      { wrong: "«Hacer una reserva»", right: "«Acordar con la familia»" },
    ],
    secTitle: "Seguridad y confianza", secDesc: "Cada familia es verificada. Seguro y soporte 24/7.",
    secFeatures: ["✅ Verificación de documentos", "🔒 Pagos seguros", "📞 Soporte 24/7", "⭐ Calificaciones"],
    ctaTitle: "Entra — conviértete en parte de una gran familia armenia",
    ctaSub: "No importa de dónde vengas. Lo que importa es tu apertura a lo nuevo.",
  },
  ar: {
    heroTitle: "من نحن", heroSub: "لا نبني منصة إيجار.\nنبني شبكة ثقافية حية.",
    missionLabel: "مهمتنا", missionTitle: "أرمينيا تنفتح", missionTitleRed: "من خلال قلب عائلة",
    missionSub: "HayHome ليست Airbnb. إنها شيء أكبر — نظام بيئي ثقافي على نطاق وطني.",
    card1t: "الحفاظ على التقاليد", card1d: "كل عائلة هي حارسة للتراث الثقافي.", card2t: "توحيد الشعوب", card2d: "ضيوف من أكثر من 40 دولة اكتشفوا أرمينيا.",
    card3t: "الفخر الوطني", card3d: "تحصل العائلات الأرمينية على لقب «حارس التقاليد».",
    storyLabel: "كيف بدأ كل شيء", storyTitle: "فكرة وُلدت على العشاء",
    story1: "بدأ كل شيء بملاحظة بسيطة: مئات العائلات الأرمينية مستعدة لاستقبال الضيوف.", story2: "والسياح من جميع أنحاء العالم يريدون هذا بالضبط — ليس خدمة فندقية، بل تجربة حية.",
    story3: "تم إنشاء HayHome لربط هؤلاء الناس. منصة ثقة وثقافة ودفء.",
    valuesLabel: "قيمنا", valuesTitle: "لماذا لسنا Airbnb",
    v: [
      { emoji: "🏡", t: "مضيف، لا مؤجر", d: "كل مضيف هو «حارس التقاليد»." },
      { emoji: "🍽️", t: "تجربة، لا سرير", d: "الضيف يبحث عن تجربة فريدة." },
      { emoji: "✅", t: "الثقة من خلال التحقق", d: "كل عائلة خاضعة للتحقق." },
      { emoji: "🌍", t: "الأرمن يلتقون بالأرمن", d: "تتعرف العائلات الأرمينية من مناطق مختلفة على بعضها." },
      { emoji: "🎖️", t: "التلعيب والمكانة", d: "شارات مثل «أفضل مطبخ» — اعتراف المجتمع." },
      { emoji: "📖", t: "قصص، لا مراجعات", d: "«جئت سائحاً وغادرت كابنهم» — هذه مراجعة حقيقية." },
    ],
    statsTitle: "HayHome اليوم",
    stats: [
      { icon: "🏡", value: "5+", label: "عائلة في الشبكة" }, { icon: "🗺️", value: "10+", label: "مناطق أرمينيا" },
      { icon: "🌍", value: "40+", label: "دول الضيوف" }, { icon: "⭐", value: "4.9★", label: "متوسط التقييم" },
    ],
    toneLabel: "صوتنا", toneTitle: "كيف نتحدث",
    toneSub: "نتحدث كأخ أكبر، مضيف مرحب — لا كشركة",
    tones: [
      { wrong: "«استخدم خدمتنا»", right: "«تفضل — نحن ننتظر»" },
      { wrong: "«مضيفون مؤهلون تأهيلاً عالياً»", right: "«عائلة أروتونيان من يريفان»" },
      { wrong: "«اترك تقييماً»", right: "«احك قصتك»" },
      { wrong: "«إجراء حجز»", right: "«الاتفاق مع العائلة»" },
    ],
    secTitle: "الأمان والثقة", secDesc: "كل عائلة تخضع للتحقق من الوثائق. تأمين ودعم 24/7.",
    secFeatures: ["✅ التحقق من الوثائق", "🔒 مدفوعات آمنة", "📞 دعم 24/7", "⭐ تقييمات ومراجعات"],
    ctaTitle: "تفضل — كن جزءاً من عائلة أرمينية كبيرة",
    ctaSub: "لا يهم من أين أنت. المهم أنك مستعد للانفتاح على شيء جديد.",
  },
  zh: {
    heroTitle: "关于我们", heroSub: "我们不是在建一个租赁平台。\n我们在建一个有生命力的文化网络。",
    missionLabel: "我们的使命", missionTitle: "亚美尼亚正在开放", missionTitleRed: "通过家庭的心",
    missionSub: "HayHome不是Airbnb。这是更多——国家规模的文化生态系统。",
    card1t: "保护传统", card1d: "每个家庭都是文化遗产的守护者。", card2t: "团结各族人民", card2d: "来自40多个国家的客人已经通过我们发现了亚美尼亚。",
    card3t: "民族自豪感", card3d: "亚美尼亚家庭获得「传统守护者」的称号。",
    storyLabel: "一切如何开始", storyTitle: "一个在晚餐时诞生的想法",
    story1: "一切始于一个简单的观察：数百个亚美尼亚家庭准备好接待客人，展示真正的热情好客。", story2: "来自世界各地的游客正是想要这些——不是酒店服务，而是真实的生活体验。",
    story3: "HayHome就是为了连接这些人而创建的。这是一个信任、文化和温暖的平台。",
    valuesLabel: "我们的价值观", valuesTitle: "为什么我们不是Airbnb",
    v: [
      { emoji: "🏡", t: "主人，不是房东", d: "每位主人都是「传统守护者」。" },
      { emoji: "🍽️", t: "体验，而非床位", d: "客人寻找独特的体验：烹饪课、共同晚餐、故事。" },
      { emoji: "✅", t: "通过验证建立信任", d: "每个家庭都经过验证。" },
      { emoji: "🌍", t: "亚美尼亚人相识", d: "来自不同地区的亚美尼亚家庭通过平台相互认识。" },
      { emoji: "🎖️", t: "游戏化和地位", d: "「最佳厨房」等徽章是社区认可。" },
      { emoji: "📖", t: "故事，不是评价", d: "「我以游客身份来，以他们的儿子身份离开」——这才是真实的评价。" },
    ],
    statsTitle: "今日HayHome",
    stats: [
      { icon: "🏡", value: "5+", label: "网络中的家庭" }, { icon: "🗺️", value: "10+", label: "亚美尼亚地区" },
      { icon: "🌍", value: "40+", label: "客人来源国" }, { icon: "⭐", value: "4.9★", label: "平均评分" },
    ],
    toneLabel: "我们的声音", toneTitle: "我们如何说话",
    toneSub: "我们像兄长、热情的主人说话——不像公司",
    tones: [
      { wrong: "«使用我们的服务»", right: "«进来——我们在等你»" },
      { wrong: "«高素质主人»", right: "«来自埃里温的阿鲁图尼扬家族»" },
      { wrong: "«留下评价»", right: "«讲述你的故事»" },
      { wrong: "«预订»", right: "«与家庭协商»" },
    ],
    secTitle: "安全与信任", secDesc: "每个家庭都经过文件验证。保险和24/7支持。",
    secFeatures: ["✅ 文件验证", "🔒 安全支付", "📞 24/7支持", "⭐ 评分和评价"],
    ctaTitle: "进来——成为一个大亚美尼亚家庭的一员",
    ctaSub: "不管你来自哪里。重要的是你愿意向新事物敞开心扉。",
  },
  fa: {
    heroTitle: "درباره ما", heroSub: "ما یک پلتفرم اجاره نمی‌سازیم.\nما یک شبکه فرهنگی زنده می‌سازیم.",
    missionLabel: "مأموریت ما", missionTitle: "ارمنستان باز می‌شود", missionTitleRed: "از طریق قلب یک خانواده",
    missionSub: "HayHome Airbnb نیست. این چیز بزرگ‌تری است — یک اکوسیستم فرهنگی در مقیاس ملی.",
    card1t: "حفظ سنت‌ها", card1d: "هر خانواده نگهبان کد فرهنگی است.", card2t: "اتحاد ملت‌ها", card2d: "مهمانانی از ۴۰+ کشور ارمنستان را کشف کرده‌اند.",
    card3t: "افتخار ملی", card3d: "خانواده‌های ارمنی عنوان «نگهبان سنت‌ها» را کسب می‌کنند.",
    storyLabel: "چگونه همه چیز شروع شد", storyTitle: "ایده‌ای که سر شام متولد شد",
    story1: "همه چیز با یک مشاهده ساده شروع شد: صدها خانواده ارمنی آماده‌اند تا مهمان بپذیرند.", story2: "و گردشگران سراسر جهان دقیقاً همین را می‌خواهند — نه خدمات هتل، بلکه تجربه زندگی.",
    story3: "HayHome برای ارتباط این مردم ایجاد شده است. پلتفرمی از اعتماد، فرهنگ و گرما.",
    valuesLabel: "ارزش‌های ما", valuesTitle: "چرا ما Airbnb نیستیم",
    v: [
      { emoji: "🏡", t: "میزبان، نه موجر", d: "هر میزبان «نگهبان سنت‌ها» است." },
      { emoji: "🍽️", t: "تجربه، نه تخت‌خواب", d: "مهمان به دنبال تجربه‌ای منحصربه‌فرد است." },
      { emoji: "✅", t: "اعتماد از طریق تأیید", d: "هر خانواده تأیید می‌شود." },
      { emoji: "🌍", t: "ارمنی‌ها با ارمنی‌ها آشنا می‌شوند", d: "خانواده‌های ارمنی از مناطق مختلف از طریق پلتفرم با هم آشنا می‌شوند." },
      { emoji: "🎖️", t: "بازی‌وارسازی و مقام", d: "نشان‌هایی مانند «بهترین آشپزخانه» — به رسمیت شناختن جامعه." },
      { emoji: "📖", t: "داستان‌ها، نه نظرات", d: "«به عنوان توریست آمدم و به عنوان پسرشان رفتم» — این یک نظر واقعی است." },
    ],
    statsTitle: "HayHome امروز",
    stats: [
      { icon: "🏡", value: "5+", label: "خانواده در شبکه" }, { icon: "🗺️", value: "10+", label: "مناطق ارمنستان" },
      { icon: "🌍", value: "40+", label: "کشورهای مهمانان" }, { icon: "⭐", value: "4.9★", label: "میانگین امتیاز" },
    ],
    toneLabel: "صدای ما", toneTitle: "چگونه صحبت می‌کنیم",
    toneSub: "ما مثل یک برادر بزرگتر، میزبانی مهمان‌نواز صحبت می‌کنیم — نه مثل یک شرکت",
    tones: [
      { wrong: "«از خدمات ما استفاده کنید»", right: "«بیا — ما منتظریم»" },
      { wrong: "«میزبانان بسیار ماهر»", right: "«خانواده آروتونیان از ایروان»" },
      { wrong: "«نظر بگذارید»", right: "«داستانت را بگو»" },
      { wrong: "«رزرو کردن»", right: "«توافق با خانواده»" },
    ],
    secTitle: "امنیت و اعتماد", secDesc: "هر خانواده تأیید اسناد می‌گذرد. بیمه و پشتیبانی ۲۴/۷.",
    secFeatures: ["✅ تأیید اسناد", "🔒 پرداخت‌های امن", "📞 پشتیبانی ۲۴/۷", "⭐ امتیازات و نظرات"],
    ctaTitle: "بیا — بخشی از یک خانواده بزرگ ارمنی شو",
    ctaSub: "مهم نیست از کجا می‌آیید. مهم این است که آماده باشید.",
  },
  it: {
    heroTitle: "Chi siamo", heroSub: "Non stiamo costruendo una piattaforma di affitti.\nStiamo costruendo una rete culturale vivente.",
    missionLabel: "La nostra missione", missionTitle: "L'Armenia si apre", missionTitleRed: "attraverso il cuore di una famiglia",
    missionSub: "HayHome non è Airbnb. È qualcosa di più — un ecosistema culturale di portata nazionale.",
    card1t: "Preservare le tradizioni", card1d: "Ogni famiglia è custode del codice culturale.", card2t: "Unire i popoli", card2d: "Ospiti da 40+ paesi hanno già scoperto l'Armenia.",
    card3t: "Orgoglio nazionale", card3d: "Le famiglie armene guadagnano lo status di «Custode delle tradizioni».",
    storyLabel: "Come è iniziato", storyTitle: "Un'idea nata a cena",
    story1: "Tutto è iniziato con una semplice osservazione: centinaia di famiglie armene sono pronte ad accogliere ospiti.", story2: "E i turisti di tutto il mondo vogliono esattamente questo — non un servizio alberghiero, ma un'esperienza viva.",
    story3: "HayHome è stato creato per connettere queste persone. Una piattaforma di fiducia, cultura e calore.",
    valuesLabel: "I nostri valori", valuesTitle: "Perché non siamo Airbnb",
    v: [
      { emoji: "🏡", t: "Host, non proprietario", d: "Ogni host è un «Custode delle tradizioni»." },
      { emoji: "🍽️", t: "Esperienza, non letto", d: "L'ospite cerca un'esperienza unica." },
      { emoji: "✅", t: "Fiducia tramite verifica", d: "Ogni famiglia viene verificata." },
      { emoji: "🌍", t: "Gli armeni si incontrano", d: "Le famiglie armene di diverse regioni si conoscono." },
      { emoji: "🎖️", t: "Gamification e status", d: "Badge come «Migliore cucina» — riconoscimento della comunità." },
      { emoji: "📖", t: "Storie, non recensioni", d: "«Sono venuto come turista e sono andato via come loro figlio» — questa è una vera recensione." },
    ],
    statsTitle: "HayHome oggi",
    stats: [
      { icon: "🏡", value: "5+", label: "Famiglie in rete" }, { icon: "🗺️", value: "10+", label: "Regioni dell'Armenia" },
      { icon: "🌍", value: "40+", label: "Paesi degli ospiti" }, { icon: "⭐", value: "4.9★", label: "Valutazione media" },
    ],
    toneLabel: "La nostra voce", toneTitle: "Come parliamo",
    toneSub: "Parliamo come un fratello maggiore, un host accogliente — non come un'azienda",
    tones: [
      { wrong: "«Usa il nostro servizio»", right: "«Entra — ti stiamo aspettando»" },
      { wrong: "«Host altamente qualificati»", right: "«Famiglia Arutunyan da Yerevan»" },
      { wrong: "«Lascia una recensione»", right: "«Racconta la tua storia»" },
      { wrong: "«Effettuare una prenotazione»", right: "«Accordarsi con la famiglia»" },
    ],
    secTitle: "Sicurezza e fiducia", secDesc: "Ogni famiglia viene verificata. Assicurazione e supporto 24/7.",
    secFeatures: ["✅ Verifica documenti", "🔒 Pagamenti sicuri", "📞 Supporto 24/7", "⭐ Valutazioni"],
    ctaTitle: "Entra — diventa parte di una grande famiglia armena",
    ctaSub: "Non importa da dove vieni. Ciò che conta è la tua apertura al nuovo.",
  },
  hy: {
    heroTitle: "Մեր մասին",
    heroSub: "Մենք չենք կառուցում վարձակալության հարթակ:\nՄենք կառուցում ենք կենդանի մշակութային ցանց:",
    missionLabel: "Մեր առաքելությունը",
    missionTitle: "Հայաստանը բացվում է",
    missionTitleRed: "ընտանիքի սրտի միջոցով",
    missionSub: "HayHome-ը Airbnb չէ: Սա ավելին է՝ ազգային մասշտաբի մշակութային էկոհամակարգ: Մենք պահպանում ենք հայկական ընտանեկան արժեքները և ամրապնդում Հայաստանի կերպարը որպես աշխարհի ամենահյուրընկալ ժողովուրդ:",
    card1t: "Ավանդույթների պահպանում", card1d: "Յուրաքանչյուր ընտանիք մշակութային կոդի պահապան է: Մենք օգնում ենք այդ կոդին ապրել և փոխանցվել սերունդներին:",
    card2t: "Ժողովուրդների միավորում", card2d: "40+ երկրների հյուրեր արդեն ծանաչել են Հայաստանը մեր տանտերերի միջոցով:",
    card3t: "Հպարտություն երկրի համար", card3d: "Հայկական ընտանիքները վաստակում են «Ավանդույթների պահապան» կարգավիճակ՝ համայնքի ճանաչումը:",
    storyLabel: "Ինչպես սկսվեց",
    storyTitle: "Գաղափար, որը ծնվեց ընթրիքին",
    story1: "Ամեն ինչ սկսվեց պարզ դիտարկումից՝ Հայաստանում ապրում են հարյուրավոր ընտանիքներ, որոնք պատրաստ են ընդունել հյուրեր:",
    story2: "Իսկ զբոսաշրջիկներն ամբողջ աշխարհից հենց սա են ուզում՝ ոչ թե հյուրանոցային սպասարկում, այլ կենդանի փորձ:",
    story3: "HayHome-ը ստեղծվել է այս մարդկանց միացնելու համար: Սա վստահության, մշակույթի և ջերմության հարթակ է:",
    valuesLabel: "Մեր արժեքները", valuesTitle: "Ինչու մենք չենք Airbnb",
    v: [
      { emoji: "🏡", t: "Տանտեր, ոչ թե վարձատու", d: "Յուրաքանչյուր տանտեր «Ավանդույթների պահապան» է:" },
      { emoji: "🍽️", t: "Փորձ, ոչ թե մահճակալ", d: "Հյուրը փնտրում է եզակի փորձ՝ վարպետության դասեր, ընթրիքներ, պատմություններ:" },
      { emoji: "✅", t: "Վստահություն ստուգման միջոցով", d: "Յուրաքանչյուր ընտանիք անցնում է ստուգում:" },
      { emoji: "🌍", t: "Հայերը ծանոթացնում են հայերի", d: "Տարբեր շրջանների ընտանիքներ ծանոթանում են միմյանց:" },
      { emoji: "🎖️", t: "Գեյմիֆիկացիա և կարգավիճակներ", d: "«Լավագույն խոհանոց» նշանները՝ համայնքի ճանաչում:" },
      { emoji: "📖", t: "Պատմություններ, ոչ թե կարծիքներ", d: "«Եկա որպես զբոսաշրջիկ, հեռացա որպես որդի»՝ սա է իրական ակնարկը:" },
    ],
    statsTitle: "HayHome այսօր",
    stats: [
      { icon: "🏡", value: "5+", label: "Ընտանիք ցանցում" },
      { icon: "🗺️", value: "10+", label: "Հայաստանի մարզեր" },
      { icon: "🌍", value: "40+", label: "Հյուրերի երկրներ" },
      { icon: "⭐", value: "4.9★", label: "Միջին վարկանիշ" },
    ],
    toneLabel: "Մեր ձայնը", toneTitle: "Ինչպես ենք խոսում",
    toneSub: "Մենք խոսում ենք ավագ եղբոր պես՝ հյուրընկալ տանտեր, հայրենասեր՝ առանց փառասիրության:",
    tones: [
      { wrong: "«Օգտվեք մեր ծառայությունից»", right: "«Արի՝ մենք սպասում ենք»" },
      { wrong: "«Բարձրորակ տանտերեր»", right: "«Արուտյունյան ընտանիք՝ Երևանից»" },
      { wrong: "«Թողեք կարծիք»", right: "«Պատմիր քո պատմությունը»" },
      { wrong: "«Կատարել ամրագրում»", right: "«Պայմանավորվել ընտանիքի հետ»" },
    ],
    secTitle: "Անվտանգություն և վստահություն",
    secDesc: "Յուրաքանչյուր ընտանիք անցնում է փաստաթղթերի ստուգում: Ապահովագրություն և աջակցություն 24/7:",
    secFeatures: ["✅ Փաստաթղթերի ստուգում", "🔒 Անվտանգ վճարումներ", "📞 Աջակցություն 24/7", "⭐ Վարկանիշ և կարծիքներ"],
    ctaTitle: "Արի՝ դարձիր մեծ հայկական ընտանիքի մաս",
    ctaSub: "Կարևոր չէ որտեղից եք: Կարևոր է՝ պատրաստ եք նորին:",
  },
};

// All other languages use English as fallback
const en = texts.en ?? texts.ru!;

export function getAboutTexts(lang: LangCode): AboutTexts {
  return texts[lang] ?? en;
}
