import { LangCode } from "./translations";

// ── UI Strings: dashboard, admin, partner, provider, header, footer ──
// Used as `import ui from "@/lib/ui"; ui(lang).dashboard` etc.

export interface UI {
  // Header / Nav
  dashboard: string;
  adminPanel: string;
  services: string;
  provider: string;
  // Footer
  footerTagline: string;
  madeInArmenia: string;
  armenianPlatform: string;
  // Dashboard
  myAccount: string;
  newRequests: string;
  confirmedLabel: string;
  totalBookings: string;
  earnedLabel: string;
  noBookings: string;
  bookingsTab: string;
  profileTab: string;
  calendarTab: string;
  // Common actions
  edit: string;
  save: string;
  cancel: string;
  deleteText: string;
  confirmAction: string;
  backBtn: string;
  loadingText: string;
  noData: string;
  copyText: string;
  shareText: string;
  searchText: string;
  allText: string;
  guestsLabel: string;
  statusLabel: string;
  descriptionLabel: string;
  phoneLabel: string;
  pricePerNight: string;
  nameLabel: string;
  emailLabel: string;
  roleLabel: string;
  refreshBtn: string;
  reviewBtn: string;
  submitBtn: string;
  // Status labels
  pendingStatus: string;
  confirmedStatus: string;
  completedStatus: string;
  cancelledStatus: string;
  activeStatus: string;
  pendingReviewStatus: string;
  suspendedStatus: string;
  rejectedStatus: string;
  paidStatus: string;
  requestedStatus: string;
  // Partner
  earnWith: string;
  inviteFriends: string;
  becomePartner: string;
  partnerLink: string;
  partnerDashboard: string;
  partnerCode: string;
  balance: string;
  totalEarned: string;
  referrals: string;
  requestPayout: string;
  payoutSubmitted: string;
  payoutTitle: string;
  amountLabel: string;
  methodLabel: string;
  bankTransfer: string;
  detailsLabel: string;
  detailsPlaceholder: string;
  payoutHistory: string;
  noPayouts: string;
  notPartnerTitle: string;
  notPartnerDesc: string;
  logInToBecome: string;
  logInBtn: string;
  getPartnerCode: string;
  youArePartner: string;
  yourCode: string;
  copyAndShare: string;
  scanQr: string;
  copiedText: string;
  whatPartnersDo: string;
  invitesTourists: string;
  sharesLinkDiaspora: string;
  findsFamilies: string;
  helpsRegister: string;
  yearsLabel: string;
  fromFirstDeal: string;
  copyLink: string;
  // Admin
  platformManagement: string;
  activeFamilies: string;
  pendingReviewAdmin: string;
  revenue: string;
  hostsTab: string;
  usersTab: string;
  payoutsTab: string;
  statisticsTab: string;
  calendarTabAdmin: string;
  servicesTab: string;
  approve: string;
  reject: string;
  completeBtn: string;
  suspend: string;
  restore: string;
  addNote: string;
  history: string;
  noRecords: string;
  noBookingsAdmin: string;
  noPayoutRequests: string;
  noUsers: string;
  searchByName: string;
  referral: string;
  dateLabel: string;
  familiesByRegion: string;
  bookingsByStatus: string;
  serviceName: string;
  categoryLabel: string;
  priceLabel: string;
  serviceStatusLabel: string;
  hiddenStatus: string;
  allServices: string;
  serviceOrders: string;
  noServicesAdmin: string;
  noOrdersAdmin: string;
  pay: string;
  rejectionReason: string;
  // Calendar
  clickToToggle: string;
  openFullCalendar: string;
  // Additional services
  additionalServices: string;
  // Provider
  providerDashboard: string;
  myServices: string;
  orders: string;
  addService: string;
  noServicesYet: string;
  noOrdersYet: string;
  titleLabel: string;
  selectRegion: string;
  customCategory: string;
  availableLabel: string;
  priceUnit: string;
  deleteServiceConfirm: string;
  // Months
  months: string[];
  // Misc
  wantToHost: string;
  registerCta: string;
  route: string;
  showRoute: string;
  allowGeo: string;
  guestProfile: string;
  accountDetails: string;
  noEmailUsers: string;
  idram: string;
  crypto: string;
}

type Rec = Record<string, string>;

const translations: Record<LangCode, UI> = {
  ru: {
    dashboard: "Личный кабинет",
    adminPanel: "Админ-панель",
    services: "Услуги",
    provider: "Кабинет",
    footerTagline: "Армения ждёт вас — не в отеле, а дома.",
    madeInArmenia: "Сделано с ❤️ в Армении",
    armenianPlatform: "🇦🇲 Платформа армянского гостеприимства.",
    myAccount: "Личный кабинет",
    newRequests: "Новых заявок",
    confirmedLabel: "Подтверждённых",
    totalBookings: "Всего бронирований",
    earnedLabel: "Заработано",
    noBookings: "Пока нет заявок",
    bookingsTab: "Бронирования",
    profileTab: "Профиль",
    calendarTab: "Календарь",
    edit: "Редактировать",
    save: "Сохранить",
    cancel: "Отмена",
    deleteText: "Удалить",
    confirmAction: "Подтвердить",
    backBtn: "Назад",
    loadingText: "Загрузка...",
    noData: "Нет данных",
    copyText: "Копировать",
    shareText: "Поделиться",
    searchText: "Поиск...",
    allText: "Все",
    guestsLabel: "гост.",
    statusLabel: "Статус",
    descriptionLabel: "Описание",
    phoneLabel: "Телефон",
    pricePerNight: "Цена за ночь",
    nameLabel: "Имя",
    emailLabel: "Эл. почта",
    roleLabel: "Роль",
    refreshBtn: "Обновить",
    reviewBtn: "Отзыв",
    submitBtn: "Отправить",
    pendingStatus: "Ожидает",
    confirmedStatus: "Подтверждено",
    completedStatus: "Завершено",
    cancelledStatus: "Отменено",
    activeStatus: "Активен",
    pendingReviewStatus: "На проверке",
    suspendedStatus: "Приостановлен",
    rejectedStatus: "Отклонён",
    paidStatus: "Выплачен",
    requestedStatus: "Запрошен",
    earnWith: "🤝 Зарабатывайте с HayHome",
    inviteFriends: "Приглашайте друзей и получайте 5% от их бронирований",
    becomePartner: "Стать партнёром",
    partnerLink: "🤝 Ваша партнёрская ссылка — делитесь с друзьями",
    partnerDashboard: "Панель партнёра",
    partnerCode: "Код:",
    balance: "Баланс",
    totalEarned: "Всего заработано",
    referrals: "Приведено",
    requestPayout: "Запросить вывод",
    payoutSubmitted: "Заявка отправлена!",
    payoutTitle: "Вывод средств",
    amountLabel: "Сумма ($)",
    methodLabel: "Способ",
    bankTransfer: "Банковский перевод",
    detailsLabel: "Реквизиты",
    detailsPlaceholder: "Номер телефона / карты / кошелька",
    payoutHistory: "История выплат",
    noPayouts: "Пока нет выплат",
    notPartnerTitle: "Вы ещё не партнёр",
    notPartnerDesc: "Станьте партнёром и начните зарабатывать",
    logInToBecome: "Войдите в аккаунт",
    logInBtn: "Войти",
    getPartnerCode: "Получить код партнёра",
    youArePartner: "Вы теперь партнёр!",
    yourCode: "Ваш код:",
    copyAndShare: "Скопируйте ссылку и делитесь",
    scanQr: "Отсканируйте QR-код",
    copiedText: "Скопировано!",
    whatPartnersDo: "Что делает партнёр",
    invitesTourists: "Привлекает туристов",
    sharesLinkDiaspora: "Делится ссылкой с туристами и диаспорой",
    findsFamilies: "Находит семьи",
    helpsRegister: "Помогает семьям и мастерам зарегистрироваться",
    yearsLabel: "года",
    fromFirstDeal: "С первой сделки, вывод от $30/мес",
    copyLink: "Копировать ссылку",
    platformManagement: "Управление платформой",
    activeFamilies: "Активных семей",
    pendingReviewAdmin: "На проверке",
    revenue: "Выручка (завершённые)",
    hostsTab: "Хозяева",
    usersTab: "Пользователи",
    payoutsTab: "Выплаты",
    statisticsTab: "Статистика",
    calendarTabAdmin: "Календарь",
    servicesTab: "Услуги",
    approve: "Одобрить",
    reject: "Отклонить",
    completeBtn: "Завершить",
    suspend: "Приостановить",
    restore: "Восстановить",
    addNote: "Добавить заметку...",
    history: "История",
    noRecords: "Нет записей",
    noBookingsAdmin: "Нет бронирований",
    noPayoutRequests: "Нет запросов на вывод",
    noUsers: "Нет пользователей",
    searchByName: "Поиск по имени или email...",
    referral: "Реферал",
    dateLabel: "Дата",
    familiesByRegion: "Семьи по регионам",
    bookingsByStatus: "Бронирования по статусу",
    serviceName: "Услуга",
    categoryLabel: "Категория",
    priceLabel: "Цена",
    serviceStatusLabel: "Статус",
    hiddenStatus: "Скрыта",
    allServices: "Все услуги",
    serviceOrders: "Заказы услуг",
    noServicesAdmin: "Услуг пока нет",
    noOrdersAdmin: "Заказов пока нет",
    pay: "Выплатить",
    rejectionReason: "Причина отклонения (опционально):",
    clickToToggle: "Нажмите на дату, чтобы заблокировать/разблокировать",
    openFullCalendar: "Открыть полный календарь →",
    additionalServices: "Дополнительные услуги:",
    providerDashboard: "Кабинет специалиста",
    myServices: "Мои услуги",
    orders: "Заказы",
    addService: "Добавить услугу",
    noServicesYet: "У вас пока нет услуг",
    noOrdersYet: "Заказов пока нет",
    titleLabel: "Название",
    selectRegion: "Выберите регион",
    customCategory: "Своя категория",
    availableLabel: "Доступно",
    priceUnit: "Единица цены",
    deleteServiceConfirm: "Удалить услугу?",
    wantToHost: "Хотите стать хозяином?",
    registerCta: "Зарегистрироваться →",
    route: "Маршрут",
    showRoute: "Показать маршрут",
    allowGeo: "Разрешите доступ к геолокации",
    guestProfile: "Профиль гостя",
    accountDetails: "Ваши данные аккаунта",
    noEmailUsers: "Все",
    idram: "Idram",
    crypto: "Крипта",
    months: ["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"],
  },

  en: {
    dashboard: "Dashboard",
    adminPanel: "Admin Panel",
    services: "Services",
    provider: "Provider",
    footerTagline: "Armenia is waiting for you — not in a hotel, but at home.",
    madeInArmenia: "Made with ❤️ in Armenia",
    armenianPlatform: "🇦🇲 Armenian hospitality platform.",
    myAccount: "Dashboard",
    newRequests: "New requests",
    confirmedLabel: "Confirmed",
    totalBookings: "Total bookings",
    earnedLabel: "Earned",
    noBookings: "No bookings yet",
    bookingsTab: "Bookings",
    profileTab: "Profile",
    calendarTab: "Calendar",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    deleteText: "Delete",
    confirmAction: "Confirm",
    backBtn: "Back",
    loadingText: "Loading...",
    noData: "No data",
    copyText: "Copy",
    shareText: "Share",
    searchText: "Search...",
    allText: "All",
    guestsLabel: "guests",
    statusLabel: "Status",
    descriptionLabel: "Description",
    phoneLabel: "Phone",
    pricePerNight: "Price/night",
    nameLabel: "Name",
    emailLabel: "Email",
    roleLabel: "Role",
    refreshBtn: "Refresh",
    reviewBtn: "Review",
    submitBtn: "Submit",
    pendingStatus: "Pending",
    confirmedStatus: "Confirmed",
    completedStatus: "Completed",
    cancelledStatus: "Cancelled",
    activeStatus: "Active",
    pendingReviewStatus: "Pending",
    suspendedStatus: "Suspended",
    rejectedStatus: "Rejected",
    paidStatus: "Paid",
    requestedStatus: "Requested",
    earnWith: "🤝 Earn with HayHome",
    inviteFriends: "Invite friends and earn 5% from their bookings",
    becomePartner: "Become a Partner",
    partnerLink: "🤝 Your referral link — share with friends",
    partnerDashboard: "Partner Dashboard",
    partnerCode: "Code:",
    balance: "Balance",
    totalEarned: "Total earned",
    referrals: "Referrals",
    requestPayout: "Request Payout",
    payoutSubmitted: "Payout request submitted!",
    payoutTitle: "Payout",
    amountLabel: "Amount ($)",
    methodLabel: "Method",
    bankTransfer: "Bank Transfer",
    detailsLabel: "Details",
    detailsPlaceholder: "Phone / card / wallet",
    payoutHistory: "Payout History",
    noPayouts: "No payouts yet",
    notPartnerTitle: "Not a partner yet",
    notPartnerDesc: "Become a partner and start earning",
    logInToBecome: "Log in",
    logInBtn: "Log In",
    getPartnerCode: "Get partner code",
    youArePartner: "You're now a partner!",
    yourCode: "Your code:",
    copyAndShare: "Copy the link and share it",
    scanQr: "Scan the QR code",
    copiedText: "Copied!",
    whatPartnersDo: "What partners do",
    invitesTourists: "Invites tourists",
    sharesLinkDiaspora: "Shares link with tourists & diaspora",
    findsFamilies: "Finds families",
    helpsRegister: "Helps families & artisans register",
    yearsLabel: "years",
    fromFirstDeal: "From first deal, min $30/mo",
    copyLink: "Copy link",
    platformManagement: "Platform Management",
    activeFamilies: "Active families",
    pendingReviewAdmin: "Pending review",
    revenue: "Revenue (completed)",
    hostsTab: "Hosts",
    usersTab: "Users",
    payoutsTab: "Payouts",
    statisticsTab: "Statistics",
    calendarTabAdmin: "Calendar",
    servicesTab: "Services",
    approve: "Approve",
    reject: "Reject",
    completeBtn: "Complete",
    suspend: "Suspend",
    restore: "Restore",
    addNote: "Add note...",
    history: "History",
    noRecords: "No records",
    noBookingsAdmin: "No bookings",
    noPayoutRequests: "No payout requests",
    noUsers: "No users",
    searchByName: "Search by name or email...",
    referral: "Referral",
    dateLabel: "Date",
    familiesByRegion: "Families by region",
    bookingsByStatus: "Bookings by status",
    serviceName: "Service",
    categoryLabel: "Category",
    priceLabel: "Price",
    serviceStatusLabel: "Status",
    hiddenStatus: "Hidden",
    allServices: "All Services",
    serviceOrders: "Service Orders",
    noServicesAdmin: "No services yet",
    noOrdersAdmin: "No orders yet",
    pay: "Pay",
    rejectionReason: "Rejection reason (optional):",
    clickToToggle: "Click a date to toggle blocked/available",
    openFullCalendar: "Open full calendar →",
    additionalServices: "Additional services:",
    providerDashboard: "Provider Dashboard",
    myServices: "My Services",
    orders: "Orders",
    addService: "Add Service",
    noServicesYet: "No services yet",
    noOrdersYet: "No orders yet",
    titleLabel: "Title",
    selectRegion: "Select region",
    customCategory: "Custom category",
    availableLabel: "Available",
    priceUnit: "Price unit",
    deleteServiceConfirm: "Delete service?",
    wantToHost: "Want to host?",
    registerCta: "Register →",
    route: "Route",
    showRoute: "Show route",
    allowGeo: "Allow geolocation access",
    guestProfile: "Guest Profile",
    accountDetails: "Your account details",
    noEmailUsers: "All",
    idram: "Idram",
    crypto: "Crypto",
    months: ["January","February","March","April","May","June","July","August","September","October","November","December"],
  },

  hy: {
    dashboard: "Անձնական կաբինետ",
    adminPanel: "Ադմին-վահանակ",
    services: "Ծառայություններ",
    provider: "Կաբինետ",
    footerTagline: "Հայաստանը սպասում է ձեզ՝ ոչ թե հյուրանոցում, այլ տանը։",
    madeInArmenia: "Ստեղծված ❤️-ով Հայաստանում",
    armenianPlatform: "🇦🇲 Հայկական հյուրընկալության հարթակ։",
    myAccount: "Անձնական կաբինետ",
    newRequests: "Նոր հայտեր",
    confirmedLabel: "Հաստատված",
    totalBookings: "Ընդհանուր ամրագրումներ",
    earnedLabel: "Վաստակված",
    noBookings: "Դեռևս ամրագրումներ չկան",
    bookingsTab: "Ամրագրումներ",
    profileTab: "Պրոֆիլ",
    calendarTab: "Օրացույց",
    edit: "Խմբագրել",
    save: "Պահպանել",
    cancel: "Չեղարկել",
    deleteText: "Ջնջել",
    confirmAction: "Հաստատել",
    backBtn: "Հետ",
    loadingText: "Բեռնում...",
    noData: "Տվյալներ չկան",
    copyText: "Պատճենել",
    shareText: "Կիսվել",
    searchText: "Որոնում...",
    allText: "Բոլորը",
    guestsLabel: "հյուր",
    statusLabel: "Կարգավիճակ",
    descriptionLabel: "Նկարագրություն",
    phoneLabel: "Հեռախոս",
    pricePerNight: "Գինը մեկ գիշերվա",
    nameLabel: "Անուն",
    emailLabel: "Էլ. փոստ",
    roleLabel: "Դեր",
    refreshBtn: "Թարմացնել",
    reviewBtn: "Կարծիք",
    submitBtn: "Ուղարկել",
    pendingStatus: "Սպասում է",
    confirmedStatus: "Հաստատված",
    completedStatus: "Ավարտված",
    cancelledStatus: "Չեղարկված",
    activeStatus: "Ակտիվ",
    pendingReviewStatus: "Ստուգման տակ",
    suspendedStatus: "Կասեցված",
    rejectedStatus: "Մերժված",
    paidStatus: "Վճարված",
    requestedStatus: "Հայտված",
    earnWith: "🤝 Վաստակեք HayHome-ի հետ",
    inviteFriends: "Հրավիրեք ընկերներին և ստացեք 5% նրանց ամրագրումներից",
    becomePartner: "Դառնալ գործընկեր",
    partnerLink: "🤝 Ձեր գործընկերային հղումը — կիսվեք ընկերների հետ",
    partnerDashboard: "Գործընկերոջ վահանակ",
    partnerCode: "Կոդ՝",
    balance: "Բալանս",
    totalEarned: "Ընդհանուր վաստակված",
    referrals: "Հրավիրված",
    requestPayout: "Խնդրել վճարում",
    payoutSubmitted: "Հայտն ուղարկված է։",
    payoutTitle: "Գումարի դուրսբերում",
    amountLabel: "Գումար ($)",
    methodLabel: "Եղանակ",
    bankTransfer: "Բանկային փոխանցում",
    detailsLabel: "Մանրամասներ",
    detailsPlaceholder: "Հեռախոս / քարտ / դրամապանակ",
    payoutHistory: "Վճարումների պատմություն",
    noPayouts: "Դեռևս վճարումներ չկան",
    notPartnerTitle: "Դուք դեռ գործընկեր չեք",
    notPartnerDesc: "Դառմավ գործընկեր և սկսեք վաստակել",
    logInToBecome: "Մուտք գործեք հաշիվ",
    logInBtn: "Մուտք",
    getPartnerCode: "Ստանալ գործընկերոջ կոդ",
    youArePartner: "Դուք այժմ գործընկեր եք։",
    yourCode: "Ձեր կոդը՝",
    copyAndShare: "Պատճենեք հղումը և կիսվեք",
    scanQr: "Սկանավորեք QR կոդը",
    copiedText: "Պատճենված է։",
    whatPartnersDo: "Ի՞նչ է անում գործընկերը",
    invitesTourists: "Հրավիրում է զբոսաշրջիկների",
    sharesLinkDiaspora: "Կիսվում է հղումով զբոսաշրջիկների և սփյուռքի հետ",
    findsFamilies: "Գտնում է ընտանիքներ",
    helpsRegister: "Օգնում է ընտանիքներին և վարպետներին գրանցվել",
    yearsLabel: "տարի",
    fromFirstDeal: "Առաջին գործարքից, նվազ. $30/ամս",
    copyLink: "Պատճենել հղումը",
    platformManagement: "Հարթակի կառավարում",
    activeFamilies: "Ակտիվ ընտանիքներ",
    pendingReviewAdmin: "Ստուգման տակ",
    revenue: "Եկամուտ (ավարտված)",
    hostsTab: "Տանտերեր",
    usersTab: "Օգտատերեր",
    payoutsTab: "Վճարումներ",
    statisticsTab: "Վիճակագրություն",
    calendarTabAdmin: "Օրացույց",
    servicesTab: "Ծառայություններ",
    approve: "Հաստատել",
    reject: "Մերժել",
    completeBtn: "Ավարտել",
    suspend: "Կասեցնել",
    restore: "Վերականգնել",
    addNote: "Ավելացնել նշում...",
    history: "Պատմություն",
    noRecords: "Գրառումներ չկան",
    noBookingsAdmin: "Ամրագրումներ չկան",
    noPayoutRequests: "Չկան վճարման հայտեր",
    noUsers: "Օգտատերեր չկան",
    searchByName: "Որոնել ըստ անվան կամ email-ի...",
    referral: "Ռեֆերալ",
    dateLabel: "Ամսաթիվ",
    familiesByRegion: "Ընտանիքներ ըստ մարզերի",
    bookingsByStatus: "Ամրագրումներ ըստ կարգավիճակի",
    serviceName: "Ծառայություն",
    categoryLabel: "Կատեգորիա",
    priceLabel: "Գին",
    serviceStatusLabel: "Կարգավիճակ",
    hiddenStatus: "Թաքցված",
    allServices: "Բոլոր ծառայությունները",
    serviceOrders: "Ծառայությունների պատվերներ",
    noServicesAdmin: "Ծառայություններ դեռ չկան",
    noOrdersAdmin: "Պատվերներ դեռ չկան",
    pay: "Վճարել",
    rejectionReason: "Մերժման պատճառը (ոչ պարտադիր)՝",
    clickToToggle: "Սեղմեք ամսաթվին՝ արգելափակելու/ապաարգելափակելու",
    openFullCalendar: "Բացել ամբողջ օրացույցը →",
    additionalServices: "Լրացուցիչ ծառայություններ՝",
    providerDashboard: "Մասնագետի կաբինետ",
    myServices: "Իմ ծառայությունները",
    orders: "Պատվերներ",
    addService: "Ավելացնել ծառայություն",
    noServicesYet: "Դուք դեռ ծառայություններ չունեք",
    noOrdersYet: "Պատվերներ դեռ չկան",
    titleLabel: "Վերնագիր",
    selectRegion: "Ընտրեք մարզ",
    customCategory: "Սեփական կատեգորիա",
    availableLabel: "Հասանելի",
    priceUnit: "Գնի միավոր",
    deleteServiceConfirm: "Ջնջել ծառայությունը՞",
    wantToHost: "Ցանկանում եք դառնալ տանտեր՞",
    registerCta: "Գրանցվել →",
    route: "Երթուղի",
    showRoute: "Ցույց տալ երթուղին",
    allowGeo: "Թույլատրեք երկրաչափությունը",
    guestProfile: "Հյուրի պրոֆիլ",
    accountDetails: "Ձեր հաշվի տվյալները",
    noEmailUsers: "Բոլորը",
    idram: "Idram",
    crypto: "Կրիպտո",
    months: ["Հունվար","Փետրվար","Մարտ","Ապրիլ","Մայիս","Հունիս","Հուլիս","Օգոստոս","Սեպտեմբեր","Հոկտեմբեր","Նոյեմբեր","Դեկտեմբեր"],
  },

  fr: {
    dashboard: "Tableau de bord",
    adminPanel: "Panneau d'administration",
    services: "Services",
    provider: "Espace pro",
    footerTagline: "L'Arménie vous attend — pas à l'hôtel, mais à la maison.",
    madeInArmenia: "Fait avec ❤️ en Arménie",
    armenianPlatform: "🇦🇲 Plateforme d'hospitalité arménienne.",
    myAccount: "Mon espace",
    newRequests: "Nouvelles demandes",
    confirmedLabel: "Confirmés",
    totalBookings: "Total réservations",
    earnedLabel: "Revenus",
    noBookings: "Pas encore de réservations",
    bookingsTab: "Réservations",
    profileTab: "Profil",
    calendarTab: "Calendrier",
    edit: "Modifier",
    save: "Enregistrer",
    cancel: "Annuler",
    deleteText: "Supprimer",
    confirmAction: "Confirmer",
    backBtn: "Retour",
    loadingText: "Chargement...",
    noData: "Aucune donnée",
    copyText: "Copier",
    shareText: "Partager",
    searchText: "Rechercher...",
    allText: "Tous",
    guestsLabel: "hôtes",
    statusLabel: "Statut",
    descriptionLabel: "Description",
    phoneLabel: "Téléphone",
    pricePerNight: "Prix/nuit",
    nameLabel: "Nom",
    emailLabel: "Email",
    roleLabel: "Rôle",
    refreshBtn: "Rafraîchir",
    reviewBtn: "Avis",
    submitBtn: "Envoyer",
    pendingStatus: "En attente",
    confirmedStatus: "Confirmé",
    completedStatus: "Terminé",
    cancelledStatus: "Annulé",
    activeStatus: "Actif",
    pendingReviewStatus: "En attente",
    suspendedStatus: "Suspendu",
    rejectedStatus: "Rejeté",
    paidStatus: "Payé",
    requestedStatus: "Demandé",
    earnWith: "🤝 Gagnez avec HayHome",
    inviteFriends: "Invitez des amis et gagnez 5% de leurs réservations",
    becomePartner: "Devenir partenaire",
    partnerLink: "🤝 Votre lien de parrainage — partagez-le",
    partnerDashboard: "Espace partenaire",
    partnerCode: "Code :",
    balance: "Solde",
    totalEarned: "Total gagné",
    referrals: "Filleuls",
    requestPayout: "Demander un paiement",
    payoutSubmitted: "Demande envoyée !",
    payoutTitle: "Paiement",
    amountLabel: "Montant ($)",
    methodLabel: "Méthode",
    bankTransfer: "Virement bancaire",
    detailsLabel: "Coordonnées",
    detailsPlaceholder: "Téléphone / carte / portefeuille",
    payoutHistory: "Historique des paiements",
    noPayouts: "Aucun paiement pour l'instant",
    notPartnerTitle: "Pas encore partenaire",
    notPartnerDesc: "Devenez partenaire et commencez à gagner",
    logInToBecome: "Connectez-vous",
    logInBtn: "Connexion",
    getPartnerCode: "Obtenir le code",
    youArePartner: "Vous êtes maintenant partenaire !",
    yourCode: "Votre code :",
    copyAndShare: "Copiez le lien et partagez-le",
    scanQr: "Scannez le QR code",
    copiedText: "Copié !",
    whatPartnersDo: "Ce que font les partenaires",
    invitesTourists: "Invite des touristes",
    sharesLinkDiaspora: "Partage le lien avec touristes et diaspora",
    findsFamilies: "Trouve des familles",
    helpsRegister: "Aide les familles et artisans à s'inscrire",
    yearsLabel: "ans",
    fromFirstDeal: "Dès la 1ère transaction, min $30/mois",
    copyLink: "Copier le lien",
    platformManagement: "Gestion de la plateforme",
    activeFamilies: "Familles actives",
    pendingReviewAdmin: "En attente",
    revenue: "Revenus (terminés)",
    hostsTab: "Hôtes",
    usersTab: "Utilisateurs",
    payoutsTab: "Paiements",
    statisticsTab: "Statistiques",
    calendarTabAdmin: "Calendrier",
    servicesTab: "Services",
    approve: "Approuver",
    reject: "Rejeter",
    completeBtn: "Terminer",
    suspend: "Suspendre",
    restore: "Restaurer",
    addNote: "Ajouter une note...",
    history: "Historique",
    noRecords: "Aucun enregistrement",
    noBookingsAdmin: "Aucune réservation",
    noPayoutRequests: "Aucune demande de paiement",
    noUsers: "Aucun utilisateur",
    searchByName: "Rechercher par nom ou email...",
    referral: "Parrainage",
    dateLabel: "Date",
    familiesByRegion: "Familles par région",
    bookingsByStatus: "Réservations par statut",
    serviceName: "Service",
    categoryLabel: "Catégorie",
    priceLabel: "Prix",
    serviceStatusLabel: "Statut",
    hiddenStatus: "Masqué",
    allServices: "Tous les services",
    serviceOrders: "Commandes de services",
    noServicesAdmin: "Aucun service pour l'instant",
    noOrdersAdmin: "Aucune commande pour l'instant",
    pay: "Payer",
    rejectionReason: "Motif de rejet (optionnel) :",
    clickToToggle: "Cliquez sur une date pour bloquer/débloquer",
    openFullCalendar: "Ouvrir le calendrier complet →",
    additionalServices: "Services additionnels :",
    providerDashboard: "Espace prestataire",
    myServices: "Mes services",
    orders: "Commandes",
    addService: "Ajouter un service",
    noServicesYet: "Aucun service pour l'instant",
    noOrdersYet: "Aucune commande pour l'instant",
    titleLabel: "Titre",
    selectRegion: "Sélectionner une région",
    customCategory: "Catégorie personnalisée",
    availableLabel: "Disponible",
    priceUnit: "Unité de prix",
    deleteServiceConfirm: "Supprimer le service ?",
    wantToHost: "Vous voulez être hôte ?",
    registerCta: "S'inscrire →",
    route: "Itinéraire",
    showRoute: "Voir l'itinéraire",
    allowGeo: "Autorisez la géolocalisation",
    guestProfile: "Profil invité",
    accountDetails: "Détails de votre compte",
    noEmailUsers: "Tous",
    idram: "Idram",
    crypto: "Crypto",
    months: ["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"],
  },

  de: {
    dashboard: "Mein Bereich",
    adminPanel: "Admin-Panel",
    services: "Dienste",
    provider: "Anbieter",
    footerTagline: "Armenien wartet auf Sie — nicht im Hotel, sondern zu Hause.",
    madeInArmenia: "Mit ❤️ in Armenien gemacht",
    armenianPlatform: "🇦🇲 Armenische Gastfreiheitsplattform.",
    myAccount: "Mein Bereich",
    newRequests: "Neue Anfragen",
    confirmedLabel: "Bestätigt",
    totalBookings: "Buchungen gesamt",
    earnedLabel: "Verdient",
    noBookings: "Noch keine Buchungen",
    bookingsTab: "Buchungen",
    profileTab: "Profil",
    calendarTab: "Kalender",
    edit: "Bearbeiten",
    save: "Speichern",
    cancel: "Abbrechen",
    deleteText: "Löschen",
    confirmAction: "Bestätigen",
    backBtn: "Zurück",
    loadingText: "Laden...",
    noData: "Keine Daten",
    copyText: "Kopieren",
    shareText: "Teilen",
    searchText: "Suchen...",
    allText: "Alle",
    guestsLabel: "Gäste",
    statusLabel: "Status",
    descriptionLabel: "Beschreibung",
    phoneLabel: "Telefon",
    pricePerNight: "Preis/Nacht",
    nameLabel: "Name",
    emailLabel: "E-Mail",
    roleLabel: "Rolle",
    refreshBtn: "Aktualisieren",
    reviewBtn: "Bewertung",
    submitBtn: "Absenden",
    pendingStatus: "Ausstehend",
    confirmedStatus: "Bestätigt",
    completedStatus: "Abgeschlossen",
    cancelledStatus: "Storniert",
    activeStatus: "Aktiv",
    pendingReviewStatus: "Ausstehend",
    suspendedStatus: "Gesperrt",
    rejectedStatus: "Abgelehnt",
    paidStatus: "Bezahlt",
    requestedStatus: "Angefragt",
    earnWith: "🤝 Verdienen Sie mit HayHome",
    inviteFriends: "Laden Sie Freunde ein und verdienen Sie 5% von ihren Buchungen",
    becomePartner: "Partner werden",
    partnerLink: "🤝 Ihr Empfehlungslink — teilen Sie ihn",
    partnerDashboard: "Partner-Dashboard",
    partnerCode: "Code:",
    balance: "Guthaben",
    totalEarned: "Insgesamt verdient",
    referrals: "Empfehlungen",
    requestPayout: "Auszahlung anfordern",
    payoutSubmitted: "Anfrage gesendet!",
    payoutTitle: "Auszahlung",
    amountLabel: "Betrag ($)",
    methodLabel: "Methode",
    bankTransfer: "Banküberweisung",
    detailsLabel: "Details",
    detailsPlaceholder: "Telefon / Karte / Wallet",
    payoutHistory: "Auszahlungsverlauf",
    noPayouts: "Noch keine Auszahlungen",
    notPartnerTitle: "Noch kein Partner",
    notPartnerDesc: "Werden Sie Partner und verdienen Sie",
    logInToBecome: "Anmelden",
    logInBtn: "Anmelden",
    getPartnerCode: "Partner-Code erhalten",
    youArePartner: "Sie sind jetzt Partner!",
    yourCode: "Ihr Code:",
    copyAndShare: "Link kopieren und teilen",
    scanQr: "QR-Code scannen",
    copiedText: "Kopiert!",
    whatPartnersDo: "Was Partner tun",
    invitesTourists: "Lädt Touristen ein",
    sharesLinkDiaspora: "Teilt Link mit Touristen und Diaspora",
    findsFamilies: "Findet Familien",
    helpsRegister: "Hilft Familien und Handwerkern bei der Registrierung",
    yearsLabel: "Jahre",
    fromFirstDeal: "Ab erstem Deal, min $30/Monat",
    copyLink: "Link kopieren",
    platformManagement: "Plattformverwaltung",
    activeFamilies: "Aktive Familien",
    pendingReviewAdmin: "In Prüfung",
    revenue: "Umsatz (abgeschlossen)",
    hostsTab: "Gastgeber",
    usersTab: "Nutzer",
    payoutsTab: "Auszahlungen",
    statisticsTab: "Statistik",
    calendarTabAdmin: "Kalender",
    servicesTab: "Dienste",
    approve: "Genehmigen",
    reject: "Ablehnen",
    completeBtn: "Abschließen",
    suspend: "Sperren",
    restore: "Wiederherstellen",
    addNote: "Notiz hinzufügen...",
    history: "Verlauf",
    noRecords: "Keine Einträge",
    noBookingsAdmin: "Keine Buchungen",
    noPayoutRequests: "Keine Auszahlungsanfragen",
    noUsers: "Keine Nutzer",
    searchByName: "Nach Name oder E-Mail suchen...",
    referral: "Empfehlung",
    dateLabel: "Datum",
    familiesByRegion: "Familien nach Region",
    bookingsByStatus: "Buchungen nach Status",
    serviceName: "Dienst",
    categoryLabel: "Kategorie",
    priceLabel: "Preis",
    serviceStatusLabel: "Status",
    hiddenStatus: "Versteckt",
    allServices: "Alle Dienste",
    serviceOrders: "Dienstbestellungen",
    noServicesAdmin: "Noch keine Dienste",
    noOrdersAdmin: "Noch keine Bestellungen",
    pay: "Zahlen",
    rejectionReason: "Ablehnungsgrund (optional):",
    clickToToggle: "Klicken Sie auf ein Datum zum Sperren/Freigeben",
    openFullCalendar: "Vollständigen Kalender öffnen →",
    additionalServices: "Zusätzliche Dienste:",
    providerDashboard: "Anbieter-Dashboard",
    myServices: "Meine Dienste",
    orders: "Bestellungen",
    addService: "Dienst hinzufügen",
    noServicesYet: "Noch keine Dienste",
    noOrdersYet: "Noch keine Bestellungen",
    titleLabel: "Titel",
    selectRegion: "Region wählen",
    customCategory: "Eigene Kategorie",
    availableLabel: "Verfügbar",
    priceUnit: "Preiseinheit",
    deleteServiceConfirm: "Dienst löschen?",
    wantToHost: "Möchten Sie Gastgeber werden?",
    registerCta: "Registrieren →",
    route: "Route",
    showRoute: "Route anzeigen",
    allowGeo: "Geolokalisierung erlauben",
    guestProfile: "Gastprofil",
    accountDetails: "Ihre Kontodaten",
    noEmailUsers: "Alle",
    idram: "Idram",
    crypto: "Krypto",
    months: ["Januar","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"],
  },

  es: {
    dashboard: "Mi espacio",
    adminPanel: "Panel de administración",
    services: "Servicios",
    provider: "Proveedor",
    footerTagline: "Armenia te espera — no en un hotel, sino en casa.",
    madeInArmenia: "Hecho con ❤️ en Armenia",
    armenianPlatform: "🇦🇲 Plataforma de hospitalidad armenia.",
    myAccount: "Mi espacio",
    newRequests: "Nuevas solicitudes",
    confirmedLabel: "Confirmados",
    totalBookings: "Reservas totales",
    earnedLabel: "Ganado",
    noBookings: "Aún no hay reservas",
    bookingsTab: "Reservas",
    profileTab: "Perfil",
    calendarTab: "Calendario",
    edit: "Editar",
    save: "Guardar",
    cancel: "Cancelar",
    deleteText: "Eliminar",
    confirmAction: "Confirmar",
    backBtn: "Atrás",
    loadingText: "Cargando...",
    noData: "Sin datos",
    copyText: "Copiar",
    shareText: "Compartir",
    searchText: "Buscar...",
    allText: "Todos",
    guestsLabel: "huéspedes",
    statusLabel: "Estado",
    descriptionLabel: "Descripción",
    phoneLabel: "Teléfono",
    pricePerNight: "Precio/noche",
    nameLabel: "Nombre",
    emailLabel: "Correo",
    roleLabel: "Rol",
    refreshBtn: "Actualizar",
    reviewBtn: "Reseña",
    submitBtn: "Enviar",
    pendingStatus: "Pendiente",
    confirmedStatus: "Confirmado",
    completedStatus: "Completado",
    cancelledStatus: "Cancelado",
    activeStatus: "Activo",
    pendingReviewStatus: "Pendiente",
    suspendedStatus: "Suspendido",
    rejectedStatus: "Rechazado",
    paidStatus: "Pagado",
    requestedStatus: "Solicitado",
    earnWith: "🤝 Gana con HayHome",
    inviteFriends: "Invita amigos y gana 5% de sus reservas",
    becomePartner: "Hacerse socio",
    partnerLink: "🤝 Tu enlace de referencia — compártelo",
    partnerDashboard: "Panel de socio",
    partnerCode: "Código:",
    balance: "Saldo",
    totalEarned: "Total ganado",
    referrals: "Referidos",
    requestPayout: "Solicitar pago",
    payoutSubmitted: "¡Solicitud enviada!",
    payoutTitle: "Pago",
    amountLabel: "Monto ($)",
    methodLabel: "Método",
    bankTransfer: "Transferencia bancaria",
    detailsLabel: "Datos",
    detailsPlaceholder: "Teléfono / tarjeta / billetera",
    payoutHistory: "Historial de pagos",
    noPayouts: "Aún no hay pagos",
    notPartnerTitle: "Aún no eres socio",
    notPartnerDesc: "Conviértete en socio y empieza a ganar",
    logInToBecome: "Inicia sesión",
    logInBtn: "Iniciar sesión",
    getPartnerCode: "Obtener código",
    youArePartner: "¡Ya eres socio!",
    yourCode: "Tu código:",
    copyAndShare: "Copia el enlace y compártelo",
    scanQr: "Escanea el código QR",
    copiedText: "¡Copiado!",
    whatPartnersDo: "Qué hacen los socios",
    invitesTourists: "Invita turistas",
    sharesLinkDiaspora: "Comparte enlace con turistas y diáspora",
    findsFamilies: "Encuentra familias",
    helpsRegister: "Ayuda a familias y artesanos a registrarse",
    yearsLabel: "años",
    fromFirstDeal: "Desde la primera transacción, mín $30/mes",
    copyLink: "Copiar enlace",
    platformManagement: "Gestión de plataforma",
    activeFamilies: "Familias activas",
    pendingReviewAdmin: "En revisión",
    revenue: "Ingresos (completados)",
    hostsTab: "Anfitriones",
    usersTab: "Usuarios",
    payoutsTab: "Pagos",
    statisticsTab: "Estadísticas",
    calendarTabAdmin: "Calendario",
    servicesTab: "Servicios",
    approve: "Aprobar",
    reject: "Rechazar",
    completeBtn: "Completar",
    suspend: "Suspender",
    restore: "Restaurar",
    addNote: "Añadir nota...",
    history: "Historial",
    noRecords: "Sin registros",
    noBookingsAdmin: "Sin reservas",
    noPayoutRequests: "Sin solicitudes de pago",
    noUsers: "Sin usuarios",
    searchByName: "Buscar por nombre o email...",
    referral: "Referido",
    dateLabel: "Fecha",
    familiesByRegion: "Familias por región",
    bookingsByStatus: "Reservas por estado",
    serviceName: "Servicio",
    categoryLabel: "Categoría",
    priceLabel: "Precio",
    serviceStatusLabel: "Estado",
    hiddenStatus: "Oculto",
    allServices: "Todos los servicios",
    serviceOrders: "Pedidos de servicios",
    noServicesAdmin: "Aún no hay servicios",
    noOrdersAdmin: "Aún no hay pedidos",
    pay: "Pagar",
    rejectionReason: "Motivo de rechazo (opcional):",
    clickToToggle: "Haz clic en una fecha para bloquear/disponibilidad",
    openFullCalendar: "Abrir calendario completo →",
    additionalServices: "Servicios adicionales:",
    providerDashboard: "Panel del proveedor",
    myServices: "Mis servicios",
    orders: "Pedidos",
    addService: "Añadir servicio",
    noServicesYet: "Aún no tienes servicios",
    noOrdersYet: "Aún no hay pedidos",
    titleLabel: "Título",
    selectRegion: "Seleccionar región",
    customCategory: "Categoría personalizada",
    availableLabel: "Disponible",
    priceUnit: "Unidad de precio",
    deleteServiceConfirm: "¿Eliminar servicio?",
    wantToHost: "¿Quieres ser anfitrión?",
    registerCta: "Registrarse →",
    route: "Ruta",
    showRoute: "Ver ruta",
    allowGeo: "Permita geolocalización",
    guestProfile: "Perfil de huésped",
    accountDetails: "Datos de tu cuenta",
    noEmailUsers: "Todos",
    idram: "Idram",
    crypto: "Cripto",
    months: ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
  },

  it: {
    dashboard: "Il mio spazio",
    adminPanel: "Pannello admin",
    services: "Servizi",
    provider: "Fornitore",
    footerTagline: "L'Armenia ti aspetta — non in un hotel, ma a casa.",
    madeInArmenia: "Fatto con ❤️ in Armenia",
    armenianPlatform: "🇦🇲 Piattaforma di ospitalità armena.",
    myAccount: "Il mio spazio",
    newRequests: "Nuove richieste",
    confirmedLabel: "Confermati",
    totalBookings: "Prenotazioni totali",
    earnedLabel: "Guadagnato",
    noBookings: "Nessuna prenotazione",
    bookingsTab: "Prenotazioni",
    profileTab: "Profilo",
    calendarTab: "Calendario",
    edit: "Modifica",
    save: "Salva",
    cancel: "Annulla",
    deleteText: "Elimina",
    confirmAction: "Conferma",
    backBtn: "Indietro",
    loadingText: "Caricamento...",
    noData: "Nessun dato",
    copyText: "Copia",
    shareText: "Condividi",
    searchText: "Cerca...",
    allText: "Tutti",
    guestsLabel: "ospiti",
    statusLabel: "Stato",
    descriptionLabel: "Descrizione",
    phoneLabel: "Telefono",
    pricePerNight: "Prezzo/notte",
    nameLabel: "Nome",
    emailLabel: "Email",
    roleLabel: "Ruolo",
    refreshBtn: "Aggiorna",
    reviewBtn: "Recensione",
    submitBtn: "Invia",
    pendingStatus: "In attesa",
    confirmedStatus: "Confermato",
    completedStatus: "Completato",
    cancelledStatus: "Annullato",
    activeStatus: "Attivo",
    pendingReviewStatus: "In attesa",
    suspendedStatus: "Sospeso",
    rejectedStatus: "Rifiutato",
    paidStatus: "Pagato",
    requestedStatus: "Richiesto",
    earnWith: "🤝 Guadagna con HayHome",
    inviteFriends: "Invita amici e guadagna il 5% dalle loro prenotazioni",
    becomePartner: "Diventa partner",
    partnerLink: "🤝 Il tuo link di riferimento — condividilo",
    partnerDashboard: "Dashboard partner",
    partnerCode: "Codice:",
    balance: "Saldo",
    totalEarned: "Totale guadagnato",
    referrals: "Referral",
    requestPayout: "Richiedi pagamento",
    payoutSubmitted: "Richiesta inviata!",
    payoutTitle: "Pagamento",
    amountLabel: "Importo ($)",
    methodLabel: "Metodo",
    bankTransfer: "Bonifico bancario",
    detailsLabel: "Dettagli",
    detailsPlaceholder: "Telefono / carta / portafoglio",
    payoutHistory: "Storico pagamenti",
    noPayouts: "Nessun pagamento",
    notPartnerTitle: "Non sei ancora partner",
    notPartnerDesc: "Diventa partner e inizia a guadagnare",
    logInToBecome: "Accedi",
    logInBtn: "Accedi",
    getPartnerCode: "Ottieni codice partner",
    youArePartner: "Ora sei un partner!",
    yourCode: "Il tuo codice:",
    copyAndShare: "Copia il link e condividilo",
    scanQr: "Scansiona il QR code",
    copiedText: "Copiato!",
    whatPartnersDo: "Cosa fanno i partner",
    invitesTourists: "Invita turisti",
    sharesLinkDiaspora: "Condivide link con turisti e diaspora",
    findsFamilies: "Trova famiglie",
    helpsRegister: "Aiuta famiglie e artigiani a registrarsi",
    yearsLabel: "anni",
    fromFirstDeal: "Dal primo affare, min $30/mese",
    copyLink: "Copia link",
    platformManagement: "Gestione piattaforma",
    activeFamilies: "Famiglie attive",
    pendingReviewAdmin: "In revisione",
    revenue: "Ricavi (completati)",
    hostsTab: "Host",
    usersTab: "Utenti",
    payoutsTab: "Pagamenti",
    statisticsTab: "Statistiche",
    calendarTabAdmin: "Calendario",
    servicesTab: "Servizi",
    approve: "Approva",
    reject: "Rifiuta",
    completeBtn: "Completa",
    suspend: "Sospendi",
    restore: "Ripristina",
    addNote: "Aggiungi nota...",
    history: "Cronologia",
    noRecords: "Nessun record",
    noBookingsAdmin: "Nessuna prenotazione",
    noPayoutRequests: "Nessuna richiesta di pagamento",
    noUsers: "Nessun utente",
    searchByName: "Cerca per nome o email...",
    referral: "Referral",
    dateLabel: "Data",
    familiesByRegion: "Famiglie per regione",
    bookingsByStatus: "Prenotazioni per stato",
    serviceName: "Servizio",
    categoryLabel: "Categoria",
    priceLabel: "Prezzo",
    serviceStatusLabel: "Stato",
    hiddenStatus: "Nascosto",
    allServices: "Tutti i servizi",
    serviceOrders: "Ordini di servizi",
    noServicesAdmin: "Nessun servizio",
    noOrdersAdmin: "Nessun ordine",
    pay: "Paga",
    rejectionReason: "Motivo di rifiuto (opzionale):",
    clickToToggle: "Clicca su una data per bloccare/disponibilità",
    openFullCalendar: "Apri calendario completo →",
    additionalServices: "Servizi aggiuntivi:",
    providerDashboard: "Dashboard fornitore",
    myServices: "I miei servizi",
    orders: "Ordini",
    addService: "Aggiungi servizio",
    noServicesYet: "Nessun servizio",
    noOrdersYet: "Nessun ordine",
    titleLabel: "Titolo",
    selectRegion: "Seleziona regione",
    customCategory: "Categoria personalizzata",
    availableLabel: "Disponibile",
    priceUnit: "Unità di prezzo",
    deleteServiceConfirm: "Eliminare il servizio?",
    wantToHost: "Vuoi diventare host?",
    registerCta: "Registrati →",
    route: "Percorso",
    showRoute: "Mostra percorso",
    allowGeo: "Consenti geolocalizzazione",
    guestProfile: "Profilo ospite",
    accountDetails: "Dati del tuo account",
    noEmailUsers: "Tutti",
    idram: "Idram",
    crypto: "Cripto",
    months: ["Gennaio","Febbraio","Marzo","Aprile","Maggio","Giugno","Luglio","Agosto","Settembre","Ottobre","Novembre","Dicembre"],
  },

  ar: {
    dashboard: "لوحتي",
    adminPanel: "لوحة الإدارة",
    services: "الخدمات",
    provider: "مزوّد",
    footerTagline: "أرمينيا تنتظرك — ليس في فندق، بل في البيت.",
    madeInArmenia: "صُنع بـ ❤️ في أرمينيا",
    armenianPlatform: "🇦🇲 منصة الضيافة الأرمنية.",
    myAccount: "لوحتي",
    newRequests: "طلبات جديدة",
    confirmedLabel: "مؤكدة",
    totalBookings: "إجمالي الحجوزات",
    earnedLabel: "المكتسبة",
    noBookings: "لا حجوزات بعد",
    bookingsTab: "الحجوزات",
    profileTab: "ملفي",
    calendarTab: "التقويم",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    deleteText: "حذف",
    confirmAction: "تأكيد",
    backBtn: "رجوع",
    loadingText: "جار التحميل...",
    noData: "لا بيانات",
    copyText: "نسخ",
    shareText: "مشاركة",
    searchText: "بحث...",
    allText: "الكل",
    guestsLabel: "ضيوف",
    statusLabel: "الحالة",
    descriptionLabel: "الوصف",
    phoneLabel: "الهاتف",
    pricePerNight: "السعر/ليلة",
    nameLabel: "الاسم",
    emailLabel: "البريد الإلكتروني",
    roleLabel: "الدور",
    refreshBtn: "تحديث",
    reviewBtn: "تقييم",
    submitBtn: "إرسال",
    pendingStatus: "قيد الانتظار",
    confirmedStatus: "مؤكد",
    completedStatus: "مكتمل",
    cancelledStatus: "ملغي",
    activeStatus: "نشط",
    pendingReviewStatus: "قيد المراجعة",
    suspendedStatus: "معلق",
    rejectedStatus: "مرفوض",
    paidStatus: "مدفوع",
    requestedStatus: "مطلوب",
    earnWith: "🤝 اربح مع HayHome",
    inviteFriends: "ادعُ أصدقاءك واكسب 5% من حجوزاتهم",
    becomePartner: "كن شريكاً",
    partnerLink: "🤝 رابط الإحالة — شاركه مع الأصدقاء",
    partnerDashboard: "لوحة الشريك",
    partnerCode: "الرمز:",
    balance: "الرصيد",
    totalEarned: "إجمالي الأرباح",
    referrals: "الإحالات",
    requestPayout: "طلب الدفع",
    payoutSubmitted: "تم إرسال الطلب!",
    payoutTitle: "الدفع",
    amountLabel: "المبلغ ($)",
    methodLabel: "الطريقة",
    bankTransfer: "تحويل بنكي",
    detailsLabel: "التفاصيل",
    detailsPlaceholder: "هاتف / بطاقة / محفظة",
    payoutHistory: "سجل المدفوعات",
    noPayouts: "لا مدفوعات بعد",
    notPartnerTitle: "لست شريكاً بعد",
    notPartnerDesc: "كن شريكاً وابدأ الكسب",
    logInToBecome: "سجّل الدخول",
    logInBtn: "تسجيل الدخول",
    getPartnerCode: "احصل على رمز الشريك",
    youArePartner: "أنت الآن شريك!",
    yourCode: "رمزك:",
    copyAndShare: "انسخ الرابط وشاركه",
    scanQr: "امسح رمز QR",
    copiedText: "تم النسخ!",
    whatPartnersDo: "ماذا يفعل الشركاء",
    invitesTourists: "يدعو السياح",
    sharesLinkDiaspora: "يشارك الرابط مع السياح والشتات",
    findsFamilies: "يجد عائلات",
    helpsRegister: "يساعد العائلات والحرفيين على التسجيل",
    yearsLabel: "سنوات",
    fromFirstDeal: "من أول صفقة، أدنى $30/شهر",
    copyLink: "نسخ الرابط",
    platformManagement: "إدارة المنصة",
    activeFamilies: "العائلات النشطة",
    pendingReviewAdmin: "قيد المراجعة",
    revenue: "الإيرادات (مكتملة)",
    hostsTab: "المضيفون",
    usersTab: "المستخدمون",
    payoutsTab: "المدفوعات",
    statisticsTab: "الإحصائيات",
    calendarTabAdmin: "التقويم",
    servicesTab: "الخدمات",
    approve: "موافقة",
    reject: "رفض",
    completeBtn: "إكمال",
    suspend: "تعليق",
    restore: "استعادة",
    addNote: "إضافة ملاحظة...",
    history: "السجل",
    noRecords: "لا سجلات",
    noBookingsAdmin: "لا حجوزات",
    noPayoutRequests: "لا طلبات دفع",
    noUsers: "لا مستخدمين",
    searchByName: "ابحث بالاسم أو البريد الإلكتروني...",
    referral: "إحالة",
    dateLabel: "التاريخ",
    familiesByRegion: "العائلات حسب المنطقة",
    bookingsByStatus: "الحجوزات حسب الحالة",
    serviceName: "الخدمة",
    categoryLabel: "الفئة",
    priceLabel: "السعر",
    serviceStatusLabel: "الحالة",
    hiddenStatus: "مخفي",
    allServices: "جميع الخدمات",
    serviceOrders: "طلبات الخدمات",
    noServicesAdmin: "لا خدمات بعد",
    noOrdersAdmin: "لا طلبات بعد",
    pay: "دفع",
    rejectionReason: "سبب الرفض (اختياري):",
    clickToToggle: "انقر على تاريخ للتبديل بين محظور/متاح",
    openFullCalendar: "افتح التقويم الكامل →",
    additionalServices: "خدمات إضافية:",
    providerDashboard: "لوحة المزوّد",
    myServices: "خدماتي",
    orders: "الطلبات",
    addService: "إضافة خدمة",
    noServicesYet: "لا خدمات بعد",
    noOrdersYet: "لا طلبات بعد",
    titleLabel: "العنوان",
    selectRegion: "اختر المنطقة",
    customCategory: "فئة مخصصة",
    availableLabel: "متاح",
    priceUnit: "وحدة السعر",
    deleteServiceConfirm: "حذف الخدمة؟",
    wantToHost: "تريد أن تصبح مضيفاً؟",
    registerCta: "سجّل →",
    route: "الطريق",
    showRoute: "إظهار الطريق",
    allowGeo: "اسمح بالموقع",
    guestProfile: "ملف الضيف",
    accountDetails: "بيانات حسابك",
    noEmailUsers: "الكل",
    idram: "Idram",
    crypto: "عملة رقمية",
    months: ["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"],
  },

  zh: {
    dashboard: "控制台",
    adminPanel: "管理面板",
    services: "服务",
    provider: "服务商",
    footerTagline: "亚美尼亚在等你——不是在酒店，而是在家。",
    madeInArmenia: "用 ❤️ 在亚美尼亚制作",
    armenianPlatform: "🇦🇲 亚美尼亚好客平台。",
    myAccount: "我的控制台",
    newRequests: "新请求",
    confirmedLabel: "已确认",
    totalBookings: "总预订",
    earnedLabel: "已赚取",
    noBookings: "暂无预订",
    bookingsTab: "预订",
    profileTab: "资料",
    calendarTab: "日历",
    edit: "编辑",
    save: "保存",
    cancel: "取消",
    deleteText: "删除",
    confirmAction: "确认",
    backBtn: "返回",
    loadingText: "加载中...",
    noData: "无数据",
    copyText: "复制",
    shareText: "分享",
    searchText: "搜索...",
    allText: "全部",
    guestsLabel: "位客人",
    statusLabel: "状态",
    descriptionLabel: "描述",
    phoneLabel: "电话",
    pricePerNight: "价格/晚",
    nameLabel: "姓名",
    emailLabel: "邮箱",
    roleLabel: "角色",
    refreshBtn: "刷新",
    reviewBtn: "评价",
    submitBtn: "提交",
    pendingStatus: "待处理",
    confirmedStatus: "已确认",
    completedStatus: "已完成",
    cancelledStatus: "已取消",
    activeStatus: "活跃",
    pendingReviewStatus: "待审核",
    suspendedStatus: "已暂停",
    rejectedStatus: "已拒绝",
    paidStatus: "已支付",
    requestedStatus: "已请求",
    earnWith: "🤝 与HayHome一起赚钱",
    inviteFriends: "邀请朋友，赚取他们预订的5%",
    becomePartner: "成为合作伙伴",
    partnerLink: "🤝 您的推荐链接——与朋友分享",
    partnerDashboard: "合作伙伴面板",
    partnerCode: "代码：",
    balance: "余额",
    totalEarned: "总计赚取",
    referrals: "推荐",
    requestPayout: "请求付款",
    payoutSubmitted: "请求已提交！",
    payoutTitle: "付款",
    amountLabel: "金额 ($)",
    methodLabel: "方式",
    bankTransfer: "银行转账",
    detailsLabel: "详情",
    detailsPlaceholder: "电话 / 卡 / 钱包",
    payoutHistory: "付款记录",
    noPayouts: "暂无付款",
    notPartnerTitle: "还不是合作伙伴",
    notPartnerDesc: "成为合作伙伴并开始赚钱",
    logInToBecome: "登录",
    logInBtn: "登录",
    getPartnerCode: "获取合作伙伴代码",
    youArePartner: "您现在是合作伙伴了！",
    yourCode: "您的代码：",
    copyAndShare: "复制链接并分享",
    scanQr: "扫描二维码",
    copiedText: "已复制！",
    whatPartnersDo: "合作伙伴做什么",
    invitesTourists: "邀请游客",
    sharesLinkDiaspora: "与游客和侨民分享链接",
    findsFamilies: "寻找家庭",
    helpsRegister: "帮助家庭和工匠注册",
    yearsLabel: "年",
    fromFirstDeal: "从第一笔交易起，最低$30/月",
    copyLink: "复制链接",
    platformManagement: "平台管理",
    activeFamilies: "活跃家庭",
    pendingReviewAdmin: "待审核",
    revenue: "收入（已完成）",
    hostsTab: "房东",
    usersTab: "用户",
    payoutsTab: "付款",
    statisticsTab: "统计",
    calendarTabAdmin: "日历",
    servicesTab: "服务",
    approve: "批准",
    reject: "拒绝",
    completeBtn: "完成",
    suspend: "暂停",
    restore: "恢复",
    addNote: "添加备注...",
    history: "历史",
    noRecords: "无记录",
    noBookingsAdmin: "无预订",
    noPayoutRequests: "无付款请求",
    noUsers: "无用户",
    searchByName: "按姓名或邮箱搜索...",
    referral: "推荐",
    dateLabel: "日期",
    familiesByRegion: "按地区的家庭",
    bookingsByStatus: "按状态的预订",
    serviceName: "服务",
    categoryLabel: "类别",
    priceLabel: "价格",
    serviceStatusLabel: "状态",
    hiddenStatus: "隐藏",
    allServices: "所有服务",
    serviceOrders: "服务订单",
    noServicesAdmin: "暂无服务",
    noOrdersAdmin: "暂无订单",
    pay: "支付",
    rejectionReason: "拒绝原因（可选）：",
    clickToToggle: "点击日期切换屏蔽/可用",
    openFullCalendar: "打开完整日历 →",
    additionalServices: "附加服务：",
    providerDashboard: "服务商面板",
    myServices: "我的服务",
    orders: "订单",
    addService: "添加服务",
    noServicesYet: "暂无服务",
    noOrdersYet: "暂无订单",
    titleLabel: "标题",
    selectRegion: "选择地区",
    customCategory: "自定义类别",
    availableLabel: "可用",
    priceUnit: "价格单位",
    deleteServiceConfirm: "删除服务？",
    wantToHost: "想成为房东？",
    registerCta: "注册 →",
    route: "路线",
    showRoute: "显示路线",
    allowGeo: "允许地理定位",
    guestProfile: "客人资料",
    accountDetails: "您的账户信息",
    noEmailUsers: "全部",
    idram: "Idram",
    crypto: "加密货币",
    months: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
  },

  fa: {
    dashboard: "داشبورد من",
    adminPanel: "پنل مدیریت",
    services: "خدمات",
    provider: "تأمین‌کننده",
    footerTagline: "ارمنستان منتظر شماست — نه در هتل، بلکه در خانه.",
    madeInArmenia: "ساخته شده با ❤️ در ارمنستان",
    armenianPlatform: "🇦🇲 پلتفرم مهمان‌نوازی ارمنی.",
    myAccount: "داشبورد من",
    newRequests: "درخواست‌های جدید",
    confirmedLabel: "تأیید شده",
    totalBookings: "کل رزروها",
    earnedLabel: "کسب شده",
    noBookings: "هنوز رزروی وجود ندارد",
    bookingsTab: "رزروها",
    profileTab: "پروفایل",
    calendarTab: "تقویم",
    edit: "ویرایش",
    save: "ذخیره",
    cancel: "لغو",
    deleteText: "حذف",
    confirmAction: "تأیید",
    backBtn: "برگشت",
    loadingText: "بارگذاری...",
    noData: "داده‌ای وجود ندارد",
    copyText: "کپی",
    shareText: "اشتراک‌گذاری",
    searchText: "جستجو...",
    allText: "همه",
    guestsLabel: "مهمان",
    statusLabel: "وضعیت",
    descriptionLabel: "توضیحات",
    phoneLabel: "تلفن",
    pricePerNight: "قیمت/شب",
    nameLabel: "نام",
    emailLabel: "ایمیل",
    roleLabel: "نقش",
    refreshBtn: "به‌روزرسانی",
    reviewBtn: "نظر",
    submitBtn: "ارسال",
    pendingStatus: "در انتظار",
    confirmedStatus: "تأیید شده",
    completedStatus: "تکمیل شده",
    cancelledStatus: "لغو شده",
    activeStatus: "فعال",
    pendingReviewStatus: "در حال بررسی",
    suspendedStatus: "معلق",
    rejectedStatus: "رد شده",
    paidStatus: "پرداخت شده",
    requestedStatus: "درخواست شده",
    earnWith: "🤝 با HayHome درآمد کسب کنید",
    inviteFriends: "دوستان خود را دعوت کنید و ۵٪ از رزروهای آن‌ها کسب کنید",
    becomePartner: "تبدیل شدن به همکار",
    partnerLink: "🤝 لینک دعوت شما — آن را به اشتراک بگذارید",
    partnerDashboard: "پنل همکار",
    partnerCode: "کد:",
    balance: "موجودی",
    totalEarned: "کل درآمد",
    referrals: "معرفی‌شده‌ها",
    requestPayout: "درخواست پرداخت",
    payoutSubmitted: "درخواست ارسال شد!",
    payoutTitle: "پرداخت",
    amountLabel: "مبلغ ($)",
    methodLabel: "روش",
    bankTransfer: "انتقال بانکی",
    detailsLabel: "جزئیات",
    detailsPlaceholder: "تلفن / کارت / کیف پول",
    payoutHistory: "تاریخچه پرداخت‌ها",
    noPayouts: "هنوز پرداختی وجود ندارد",
    notPartnerTitle: "هنوز همکار نیستید",
    notPartnerDesc: "همکار شوید و شروع به کسب درآمد کنید",
    logInToBecome: "وارد شوید",
    logInBtn: "ورود",
    getPartnerCode: "دریافت کد همکار",
    youArePartner: "شما اکنون همکار هستید!",
    yourCode: "کد شما:",
    copyAndShare: "لینک را کپی و به اشتراک بگذارید",
    scanQr: "کد QR را اسکن کنید",
    copiedText: "کپی شد!",
    whatPartnersDo: "همکاران چه می‌کنند",
    invitesTourists: "دعوت از گردشگران",
    sharesLinkDiaspora: "اشتراک‌گذاری لینک با گردشگران و دیاسپورا",
    findsFamilies: "پیدا کردن خانواده‌ها",
    helpsRegister: "کمک به ثبت‌نام خانواده‌ها و صنعتگران",
    yearsLabel: "سال",
    fromFirstDeal: "از اولین معامله، حداقل $۳۰/ماه",
    copyLink: "کپی لینک",
    platformManagement: "مدیریت پلتفرم",
    activeFamilies: "خانواده‌های فعال",
    pendingReviewAdmin: "در حال بررسی",
    revenue: "درآمد (تکمیل شده)",
    hostsTab: "میزبانان",
    usersTab: "کاربران",
    payoutsTab: "پرداخت‌ها",
    statisticsTab: "آمار",
    calendarTabAdmin: "تقویم",
    servicesTab: "خدمات",
    approve: "تأیید",
    reject: "رد",
    completeBtn: "تکمیل",
    suspend: "تعلیق",
    restore: "بازگردانی",
    addNote: "افزودن یادداشت...",
    history: "تاریخچه",
    noRecords: "بدون رکورد",
    noBookingsAdmin: "بدون رزرو",
    noPayoutRequests: "بدون درخواست پرداخت",
    noUsers: "بدون کاربر",
    searchByName: "جستجو بر اساس نام یا ایمیل...",
    referral: "معرفی",
    dateLabel: "تاریخ",
    familiesByRegion: "خانواده‌ها بر اساس منطقه",
    bookingsByStatus: "رزروها بر اساس وضعیت",
    serviceName: "خدمت",
    categoryLabel: "دسته",
    priceLabel: "قیمت",
    serviceStatusLabel: "وضعیت",
    hiddenStatus: "پنهان",
    allServices: "همه خدمات",
    serviceOrders: "سفارشات خدمات",
    noServicesAdmin: "هنوز خدماتی وجود ندارد",
    noOrdersAdmin: "هنوز سفارشی وجود ندارد",
    pay: "پرداخت",
    rejectionReason: "دلیل رد (اختیاری):",
    clickToToggle: "برای مسدود/موجود کردن روی تاریخ کلیک کنید",
    openFullCalendar: "باز کردن تقویم کامل →",
    additionalServices: "خدمات اضافی:",
    providerDashboard: "پنل تأمین‌کننده",
    myServices: "خدمات من",
    orders: "سفارشات",
    addService: "افزودن خدمت",
    noServicesYet: "هنوز خدماتی ندارید",
    noOrdersYet: "هنوز سفارشی وجود ندارد",
    titleLabel: "عنوان",
    selectRegion: "انتخاب منطقه",
    customCategory: "دسته سفارشی",
    availableLabel: "موجود",
    priceUnit: "واحد قیمت",
    deleteServiceConfirm: "حذف خدمت؟",
    wantToHost: "می‌خواهید میزبان شوید؟",
    registerCta: "ثبت‌نام →",
    route: "مسیر",
    showRoute: "نمایش مسیر",
    allowGeo: "اجازه دسترسی به مکان",
    guestProfile: "پروفایل مهمان",
    accountDetails: "اطلاعات حساب شما",
    noEmailUsers: "همه",
    idram: "Idram",
    crypto: "کریپتو",
    months: ["ژانویه","فوریه","مارس","آوریل","مه","ژوئن","ژوئیه","اوت","سپتامبر","اکتبر","نوامبر","دسامبر"],
  },
};

export default function getUI(lang: LangCode): UI {
  return translations[lang] || translations.en;
}
